# AEGIS IDEA3 PR11 Phase 4 — Recovery NON-CONSUMING PRE-LIVE REHEARSAL driver (library). NOT AN AUTHORITY. NOT AN AUTHORIZATION.
#
# This file defines functions only; it executes nothing when sourced. It is embedded by recovery_rehearsal_build.py into a DERIVED COPY of a frozen
# Recovery runner, in place of that runner's final `recovery_run_attempt` call. The frozen runner itself is never modified, sourced from here, or rerun.
#
# What the rehearsal DOES: after the runner's own prefix has passed (pins, environment gate, control-snapshot gates, operator identity, ONE sudo
# establishment), it runs the runner's EXISTING read-only checks exactly as the live runner runs them before the marker:
#   recovery_hook_pregates   (exact-main, authorization/K3, real stage gate, R1B/R1Bv predecessor, CTu-or-CTv-PASS successor, RRu, attempt unconsumed,
#                             disk/services/broker/IDEA2 S10, the live authority gates, Recovery socket, owner reason)
#   recovery_hook_regate     (live authority again, sudo authority, terminal, attempt unconsumed)
#   a release-CLI argument-parse check (`aegisctl restore --help`, which exits in argparse BEFORE the restore command can run)
# and it reports each section as PASS, BLOCKED or NOT_REHEARSED.
#
# What it CANNOT and MUST NOT do: it never consumes the Recovery attempt, creates no marker, no work directory, no provenance file, no capture and no
# closeout, runs no baseline/ISOLATE/RESTORE/CLOSE/FINAL/VERIFY, issues no device command, and restarts nothing. Every consuming or mutating runner function is
# replaced by a tripwire; every privileged command goes through a default-deny read-only wrapper. A PASS here means ONLY "these checks passed just now":
# it is not Recovery authorization, it is not an attempt token, it carries no digest that any gate accepts, and it never replaces the live runner's own gates.

RECOVERY_REHEARSAL_STAGE="Recovery-preflight-rehearsal"
# The real sudo the read-only wrapper delegates to: a plain assignment (the environment cannot choose it). Tests replace it AFTER sourcing.
RECOVERY_REHEARSAL_REAL_SUDO=/usr/bin/sudo
RH_DIR=""
RH_TRIPPED=0

# Every runner/library function that consumes the attempt, writes into the root work directory, runs a post-marker step or issues a command. They are
# redefined as tripwires; none of them is called by the read-only checks above.
RECOVERY_REHEARSAL_POISONED="recovery_consume_attempt recovery_run_attempt recovery_attempt_failed recovery_hook_baseline recovery_hook_isolate recovery_hook_d4 recovery_hook_restore_status recovery_hook_close recovery_hook_final recovery_hook_verify recovery_hook_preserve_evidence recovery_d4_run recovery_d4_exec recovery_d4_rehearsal recovery_handler recovery_prepare_evidence recovery_capture recovery_root_py recovery_compare recovery_logs_prepare recovery_durable recovery_fsync"

recovery_rehearsal_say() { printf 'RECOVERY_REHEARSAL_%s\n' "$1"; }

# recovery_rehearsal_trip NAME — a forbidden function or privileged command was reached. The tripwire FILE is authoritative (the call may run in a subshell).
recovery_rehearsal_trip() {
  printf 'RECOVERY_REHEARSAL_TRIPWIRE=%s\n' "$1" >&2
  [ -z "${RH_DIR:-}" ] || printf '%s\n' "$1" >> "$RH_DIR/TRIPWIRE" 2>/dev/null || true
  exit 97
}

recovery_rehearsal_poison_install() {
  local fn orig
  for fn in $RECOVERY_REHEARSAL_POISONED; do
    eval "$fn() { recovery_rehearsal_trip $fn; }"
  done
  # The Core client wrapper is allowed ONLY for the two read-only subcommands the pre-gates use.
  if declare -F recovery_operator_py >/dev/null 2>&1; then
    eval "recovery_operator_py_original() $(declare -f recovery_operator_py | sed '1d')"
  else
    recovery_operator_py_original() { return 1; }
  fi
  recovery_operator_py() {
    case "${1:-}" in
      socket-check | check-reason) recovery_operator_py_original "$@" ;;
      *) recovery_rehearsal_trip "recovery_operator_py:${1:-}" ;;
    esac
  }
}

# recovery_rehearsal_write_sudo_wrapper PATH CTRL PY — a default-deny, read-only privilege wrapper. `sudo` for the pre-gates is replaced by this file. It
# peels `env`, then allows ONLY: file/process READ verbs, `systemctl show`, `nft ... list ...`, the control-snapshot python tools and `python -` stdin gates
# of the reviewed libraries (the same programs the live runner runs before the marker), and the single read-only /proc environ probe. Anything else — every
# mutation verb, `bash -c`, `systemctl` other than show, `nft` other than list, an unknown program — writes the tripwire and exits 97.
recovery_rehearsal_write_sudo_wrapper() {
  local path=$1 ctrl=$2 py=$3
  umask 077
  cat > "$path" <<'WRAPPER'
#!/bin/bash -p
# Read-only privilege wrapper generated by recovery_preflight_rehearsal.sh. Default deny.
set -u
REAL=__REAL_SUDO__
LOG=__LOG__
TRIP=__TRIP__
CTRL=__CTRL__
PY=__PY__
deny() { printf 'RECOVERY_REHEARSAL_SUDO_DENIED=%s\n' "$*" >&2; printf 'sudo:%s\n' "$*" >> "$TRIP"; exit 97; }
orig=("$@")
args=("$@")
# peel `env` (with -i, -u NAME, VAR=value) so the program behind it is the one that is judged
while [ "${args[0]:-}" = env ]; do
  args=("${args[@]:1}")
  while [ "${#args[@]}" -gt 0 ]; do
    case "${args[0]}" in
      -i) args=("${args[@]:1}") ;;
      -u) args=("${args[@]:2}") ;;
      -*) deny "env-option:${args[0]}" ;;
      *=*) args=("${args[@]:1}") ;;
      *) break ;;
    esac
  done
done
[ "${#args[@]}" -gt 0 ] || deny "empty-command"
prog=${args[0]}
base=${prog##*/}
case "$base" in
  test | stat | cat | sha256sum | readlink | grep | head | cmp | ls | pgrep | true | id | wc | sort | uniq | cut | tr | df | journalctl | date | basename | dirname) ;;
  find)
    for a in "${args[@]:1}"; do
      case "$a" in -delete | -exec | -execdir | -ok | -okdir | -fprint | -fprint0 | -fprintf | -fls) deny "find:$a" ;; esac
    done ;;
  awk)
    for a in "${args[@]:1}"; do
      case "$a" in *system\(* | *getline* | *"|"* | *'> "'* | *'>"'* | *'>>'*) deny "awk-program" ;; esac
    done ;;
  systemctl) [ "${args[1]:-}" = show ] || deny "systemctl:${args[1]:-}" ;;
  nft)
    case " ${args[*]:1} " in " list "* | " --stateless list "*) ;; *) deny "nft:${args[*]:1}" ;; esac ;;
  bash | sh)
    # the ONLY shell string allowed: the reviewed read-only /proc environ probe
    [ "${args[1]:-}" = -c ] && [ "${args[2]:-}" = 'tr "\0" "\n" < "/proc/$1/environ" | grep -qx "AEGIS_ALERT_SOURCE_UID=$2"' ] || deny "shell:${args[1]:-}" ;;
  python | python3 | python3.*)
    [ "$(readlink -f "$prog" 2>/dev/null)" = "$(readlink -f "$PY" 2>/dev/null)" ] || [ "$prog" = /usr/bin/python3 ] || deny "python-interpreter:$prog"
    i=1
    while [ "$i" -lt "${#args[@]}" ]; do
      case "${args[$i]}" in -I | -B | -s | -E | -S) i=$((i + 1)) ;; *) break ;; esac
    done
    script=${args[$i]:-}
    case "$script" in
      -) ;;                                   # a reviewed library's read-only heredoc gate on stdin
      "$CTRL"/*) ;;                           # a control-snapshot tool (frozen, root-owned, byte-identical to the pinned main)
      *) deny "python-script:$script" ;;
    esac ;;
  *) deny "program:$prog" ;;
esac
printf '%s\n' "${orig[*]}" >> "$LOG"
exec "$REAL" -n "${orig[@]}"
WRAPPER
  # fill the generated values (paths contain no sed-special characters: they are validated absolute paths)
  sed -i \
    -e "s|__REAL_SUDO__|$RECOVERY_REHEARSAL_REAL_SUDO|" \
    -e "s|__LOG__|$RH_DIR/sudo-calls.log|" \
    -e "s|__TRIP__|$RH_DIR/TRIPWIRE|" \
    -e "s|__CTRL__|$ctrl|" \
    -e "s|__PY__|$py|" "$path"
  chmod 0500 "$path"
}

# recovery_rehearsal_cleanup — idempotent; removes ONLY the private directory this rehearsal created itself.
recovery_rehearsal_cleanup() {
  recovery_stop_sudo_keepalive 2>/dev/null || true
  if [ -n "${RH_DIR:-}" ] && [[ "$RH_DIR" == */aegis-recovery-rehearsal.* ]] && [ -d "$RH_DIR" ] && [ ! -L "$RH_DIR" ]; then
    rm -rf -- "$RH_DIR"
  fi
  RH_DIR=""
}

# recovery_rehearsal_section NAME STATUS [REASON] — one result line; STATUS is exactly PASS, BLOCKED, NOT_REHEARSED or UNKNOWN.
recovery_rehearsal_section() {
  case "$2" in PASS | BLOCKED | NOT_REHEARSED | UNKNOWN) ;; *) recovery_rehearsal_trip "bad-status:$2" ;; esac
  recovery_rehearsal_say "$1=$2"
  [ -z "${3:-}" ] || recovery_rehearsal_say "$1_REASON=$(printf '%s' "$3" | tr -cd 'A-Za-z0-9_:.() -' | cut -c1-160)"
}

# recovery_rehearsal_run_gate FUNCTION... — runs one read-only check, shows at most 40 bounded reason lines, returns its status.
recovery_rehearsal_run_gate() {
  local out rc
  out=$("$@" 2>&1); rc=$?
  printf '%s\n' "$out" | tr -cd '[:print:]\n' | head -n 40 | sed 's/^/  | /'
  LAST_GATE_OUTPUT=$out
  return "$rc"
}

recovery_rehearsal_cli_parse() {
  # `aegisctl restore --help`: argparse prints usage and exits 0 before the restore command can execute. The pinned release CLI identity is already proven by
  # the authority gates; this adds import + argument-parser proof WITHOUT running the restore entry point.
  local out rc
  [[ "${RELEASE_PATH:-}" == /* ]] && [ -x "${RELEASE_PATH:-}/venv/bin/python" ] || { LAST_GATE_OUTPUT="RELEASE_PYTHON_MISSING"; return 1; }
  out=$( cd "$RELEASE_PATH" && env -i PATH="$RECOVERY_SAFE_PATH" HOME="${HOME:-/nonexistent}" TERM="${TERM:-dumb}" LANG="${LANG:-C.UTF-8}" AEGIS_RUNTIME_DIR="$RUNTIME_DIR" \
      AEGIS_LOG_PATH="$RH_DIR/cli-parse.log" PYTHONDONTWRITEBYTECODE=1 PYTHONNOUSERSITE=1 "$RELEASE_PATH/venv/bin/python" -B -s -m aegis_soc.cli restore --help </dev/null 2>&1 ); rc=$?
  LAST_GATE_OUTPUT=$out
  [ "$rc" = 0 ] && [[ "$out" == *"usage: aegisctl restore"* ]] && [[ "$out" != *Traceback* ]] && [[ "$out" != *"RESTORE refused"* ]]
}

# recovery_rehearse — the whole rehearsal. Exit statuses: 0 = every REHEARSED check passed (still NOT an authorization), 10 = at least one check is BLOCKED,
# 97 = a safety tripwire fired.
recovery_rehearse() {
  local frozen_sha=${RECOVERY_REHEARSAL_FROZEN_RUNNER_SHA256:-} blocked=0 marker canon predecessor=NO
  [[ "$frozen_sha" =~ ^[0-9a-f]{64}$ ]] || { recovery_rehearsal_say "RESULT=BLOCKED"; recovery_rehearsal_say "RESULT_REASON=FROZEN_RUNNER_SHA256_MISSING"; return 10; }
  for fn in recovery_hook_pregates recovery_hook_regate recovery_attempt_unconsumed recovery_canonical_dir; do
    declare -F "$fn" >/dev/null 2>&1 || { recovery_rehearsal_say "RESULT=BLOCKED"; recovery_rehearsal_say "RESULT_REASON=RUNNER_FUNCTION_MISSING_$fn"; return 10; }
  done
  RH_DIR=$(mktemp -d "${TMPDIR:-/tmp}/aegis-recovery-rehearsal.XXXXXX") || { recovery_rehearsal_say "RESULT=BLOCKED"; return 10; }
  chmod 700 "$RH_DIR"
  trap recovery_rehearsal_cleanup EXIT
  recovery_rehearsal_say "STAGE=$RECOVERY_REHEARSAL_STAGE"
  recovery_rehearsal_say "MODE=READ_ONLY_NON_CONSUMING_PREFLIGHT"
  recovery_rehearsal_say "FROZEN_RUNNER_SHA256=$frozen_sha"
  # The derived copy has its own digest; the Authorization names the FROZEN runner, so the pre-gates must be judged against that digest.
  RUNNER_SHA256=$frozen_sha
  recovery_rehearsal_write_sudo_wrapper "$RH_DIR/sudo-ro" "$CTRL" "$PY"
  SUDO="$RH_DIR/sudo-ro"
  recovery_rehearsal_poison_install
  canon=$(recovery_canonical_dir); marker="$canon/$RECOVERY_GLOBAL_MARKER_NAME"

  # 1. the attempt authority is unconsumed (read-only)
  if recovery_rehearsal_run_gate recovery_attempt_unconsumed; then recovery_rehearsal_section ATTEMPT_UNCONSUMED PASS
  else recovery_rehearsal_section ATTEMPT_UNCONSUMED BLOCKED "$LAST_GATE_OUTPUT"; blocked=1; fi
  # 2. the runner's complete read-only pre-gate set (collects EVERY failure, not just the first)
  if recovery_rehearsal_run_gate recovery_hook_pregates; then recovery_rehearsal_section PREGATES PASS
  else
    recovery_rehearsal_section PREGATES BLOCKED "see the GATE_FAIL lines above"; blocked=1
    case "$LAST_GATE_OUTPUT" in *"neither historical CTu PASS nor reviewed CTv PASS"* | *"predecessor gate failed"*) predecessor=YES ;; esac
  fi
  recovery_rehearsal_say "PREDECESSOR_GATE_BLOCKING=$predecessor"
  # 3. the pre-marker re-gate
  if recovery_rehearsal_run_gate recovery_hook_regate; then recovery_rehearsal_section REGATE PASS
  else recovery_rehearsal_section REGATE BLOCKED "$LAST_GATE_OUTPUT"; blocked=1; fi
  # 4. the pinned release CLI imports and parses its arguments (never runs `restore`)
  if recovery_rehearsal_run_gate recovery_rehearsal_cli_parse; then recovery_rehearsal_section RELEASE_CLI_PARSE PASS
  else recovery_rehearsal_section RELEASE_CLI_PARSE BLOCKED "$LAST_GATE_OUTPUT"; blocked=1; fi
  # 5. everything that would need a root-owned work directory, the marker or a command is NOT rehearsed — never reported as passed
  recovery_rehearsal_section BASELINE_AND_ROOT_CAPTURES NOT_REHEARSED "needs a root-owned work directory and provenance file"
  recovery_rehearsal_section D4_EXACT_TERMINAL_REFUSAL NOT_REHEARSED "would execute the restore entry point; the live runner still performs it before the marker"
  recovery_rehearsal_section ATTEMPT_MARKER NOT_REHEARSED "the marker is never created by a rehearsal"
  recovery_rehearsal_section ISOLATE_D4_RESTORE_CLOSE_FINAL_VERIFY NOT_REHEARSED "post-marker steps are never reached"

  # safety proof: nothing was consumed, no tripwire fired
  if [ -s "$RH_DIR/TRIPWIRE" ]; then
    recovery_rehearsal_say "SAFETY_TRIPWIRE=FIRED"
    sed 's/^/RECOVERY_REHEARSAL_TRIPWIRE_DETAIL=/' "$RH_DIR/TRIPWIRE" | head -n 5
    RH_TRIPPED=1
  fi
  if [ "$RH_TRIPPED" = 0 ]; then
    if $SUDO test -e "$marker" 2>/dev/null || $SUDO test -L "$marker" 2>/dev/null; then
      # an already-consumed attempt is a BLOCK that existed before the rehearsal (section 1); report it, never claim the rehearsal did or did not create it beyond section 1
      recovery_rehearsal_say "MARKER_PRESENT=YES"
    else
      recovery_rehearsal_say "MARKER_PRESENT=NO"
    fi
  fi
  recovery_rehearsal_say "ATTEMPT_CONSUMED_BY_REHEARSAL=NO"
  recovery_rehearsal_say "PRODUCTION_MUTATION_BY_REHEARSAL=NO"
  recovery_rehearsal_say "DEVICE_COMMANDS=0"
  recovery_rehearsal_say "AUTHORIZES_RECOVERY=NO"
  recovery_rehearsal_say "IS_AUTHORITY_TOKEN=NO"
  recovery_rehearsal_say "PASS_MEANS=ONLY_THE_REHEARSED_CHECKS_PASSED_JUST_NOW_NOT_AUTHORIZATION_NOT_A_GUARANTEE"
  if [ "$RH_TRIPPED" = 1 ]; then recovery_rehearsal_say "RESULT=SAFETY_TRIPWIRE"; return 97; fi
  if [ "$blocked" = 1 ]; then recovery_rehearsal_say "RESULT=BLOCKED"; return 10; fi
  recovery_rehearsal_say "RESULT=PREFLIGHT_PASS_NOT_AUTHORIZATION"
  return 0
}
