// Flat i18n table — every user-facing string flows through here.
// No hardcoded UI copy in JSX. Mock DATA (filenames, people) stays literal.
export const LANGS = ['en', 'th', 'zh']

export const STRINGS = {
  en: {
    productName: 'AEGIS Drive_LC',
    productTag: 'AUTONOMOUS EDGE-GUARD INFRASTRUCTURE SYSTEM',
    productLockupSub: 'ENTERPRISE STORAGE · SECURE HUD',
    breadcrumb: 'Breadcrumb',
    moreActions: 'More actions',
    errorBoundaryTitle: 'Something went wrong',
    errorBoundaryBody: 'This page could not be rendered. Technical details were logged to the browser console.',
    errorBoundaryReload: 'Reload',

    // login
    loginTitle: 'Sign in',
    loginSubtitle: 'Secure NAS · on-premise',
    username: 'Username',
    password: 'Password',
    usernamePlaceholder: 'your.name',
    passwordPlaceholder: '••••••••',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    rememberSession: 'Remember this session',
    signIn: 'Sign in',
    signingIn: 'Verifying…',
    loginFailed: 'Invalid username or password.',
    lockout: 'Too many attempts — locked for {s}s',
    // ── ความล้มเหลวที่ "ไม่ได้เกิดจากรหัสผ่าน" — ต้องไม่ถูกแสดงเป็น loginFailed เด็ดขาด
    loginBlockedCsrf: 'Request blocked — origin mismatch. Please reload the page and try again.',
    loginNetwork: 'Cannot reach the server. Check your connection and try again.',
    loginTimeout: 'The server took too long to respond. Please try again.',
    loginServerError: 'Server error — your credentials were not checked. Please try again.',

    // Four UI states (loading = skeleton, no strings needed)
    errLoadTitle: 'Could not load this screen',
    errLoadHint: 'The Drive backend did not respond. Check that the server is running, then try again.',
    errLoadTimeout: 'The request timed out. The Edge node may be under load — try again.',
    retry: 'Retry',
    emptyNoFiles: 'No files yet',
    emptyFolder: 'No files or folders in this location yet',
    createFirstFolder: 'Create your first folder',
    emptyNoFilesHint: 'Upload a file or create a folder to get started.',
    dependencyUnavailableHint: 'The metadata service is not connected. Data is unavailable right now; this does not mean it was deleted.',
    dashboardUnavailable: 'Dashboard data unavailable',
    filesUnavailable: 'Files are unavailable',
    sharesUnavailable: 'Secure Shares unavailable',
    historyUnavailable: 'File history unavailable',
    auditUnavailable: 'Audit log unavailable',
    accessUnavailable: 'Access Control unavailable',
    emptyNoShares: 'No active share links',
    emptyNoSharesHint: 'Create a link on the left — every link carries an expiry and a network scope.',
    emptyNoAudit: 'No audit events yet',
    emptyNoAuditHint: 'Security-relevant actions will be recorded here as they happen.',
    emptyNoUsers: 'No user accounts',
    emptyNoActivity: 'No recent activity',
    emptyNoLoginHistory: 'No login history yet',
    emptyNoRecentFiles: 'No recent files yet',
    notConnected: 'Not connected',
    driveOnline: 'Drive: online',
    driveNotConnected: 'Drive: Not connected',
    metadataNotConnected: 'Metadata: Not connected',
    metadataConnected: 'Metadata: {source}',
    emptyNoUploads: 'No uploads yet',
    emptyNoUploadsHint: 'Drop files above to upload them to the current folder.',
    dashLoginHistory: 'Login history',
    dashLoginHistorySub: 'Your recent sign-ins — personal security status',
    statSecurity: 'DENIED/BLOCKED events (latest 100)',
    stFailed: 'Failed',
    uploadTooLarge: 'Larger than the 1 GB upload limit — this file was not sent.',
    confirmDeleteTitle: 'Delete from the data lake?',
    confirmDeleteBody: '“{name}” and its entire version history are deleted permanently. There is no trash and nothing restores it.',
    actionFailed: 'The action failed — the server did not accept the request. Try again.',
    layerNetwork: 'LAYER 0 · NETWORK',
    layerNetworkDesc: 'VPN + VLAN',
    layerApp: 'LAYER 1 · APPLICATION',
    layerAppDesc: 'Credentials',
    layerStorage: 'LAYER 2 · STORAGE',
    layerStorageDesc: 'Data Lake · not encrypted at rest',
    layerMeta: 'LAYER 3 · METADATA',
    layerMetaDesc: 'PostgreSQL',

    // nav
    navDashboard: 'Dashboard',
    navFiles: 'Files',
    navVault: 'Private Vault',
    navUploads: 'Uploads',
    navShares: 'Secure Shares',
    navVersions: 'File history',
    versionsTitle: 'File history',
    versionsMyFiles: 'Your files',
    versionsNone: 'No earlier versions',
    versionsCount: '{n} earlier versions',
    versionsEmptyHint: 'Upload a file with the same name again and the version it replaces is kept here.',
    versionsPickFile: 'Choose a file to see its history',
    versionCurrent: 'CURRENT',
    versionSupersededBy: 'replaced by',
    versionRestore: 'Restore',
    versionRestoring: 'Restoring…',
    versionRestored: 'Restored. The file that was current is now the newest earlier version.',
    versionRestoreTitle: 'Restore this version?',
    versionRestoreBody: 'The version from {when} becomes the current file.',
    versionRestoreSafe: 'Nothing is lost — the file that is current right now is kept as an earlier version, so you can undo this.',
    versionsScopeTitle: 'This is per-file history, not a snapshot of the whole Data Lake.',
    versionsScopeBody: 'Point-in-time snapshots need a filesystem that provides them (LVM, ZFS or Btrfs); this deployment stores files on a plain volume. Deleted files keep no history, and these versions sit on the same disk as the files — they do not survive a drive failure. That is what off-site backup is for, and none is configured yet.',
    versionsTrackEmpty: 'No file versions have been saved yet — a prior version appears after a file is replaced.',
    versionsNoFiles: 'No files are available for version history yet',
    notAvailable: 'Not available here',
    notConfigured: 'Not configured',
    capacitySub: 'Read from the filesystem holding the Data Lake.',
    capacityTotal: 'Total',
    capacityUsed: 'Used',
    capacityUsedPct: 'Used',
    capacityUnreadable: 'The filesystem did not report capacity, so no figure is shown rather than a guessed one.',
    unaccounted: 'Other on this volume',
    unaccountedHint: 'Space the filesystem counts as used that this application did not put there — system files, other containers sharing the volume, or orphaned data.',
    versions: 'Earlier versions',
    other: 'Other files',
    diskHealth: 'Disk Health',
    diskHealthWhy: 'Model, serial, temperature and SMART status need raw device access (smartctl with CAP_SYS_RAWIO). This container runs unprivileged as a non-root user and is not granted it, so no figures are shown. Reporting them would require a host-level change, not more code.',
    raidStatus: 'RAID',
    raidWhy: 'No array is configured in this deployment, and reading array state would need the host /proc/mdstat.',
    backupJobs: 'Backup Jobs',
    backupJobsWhy: 'No backup job or destination is configured anywhere in this deployment. Until one is, nothing here is being copied off this machine.',
    navStorage: 'Storage & Backup',
    navAudit: 'Audit Log',
    navAccess: 'Access Control',
    navSettings: 'Settings',
    navGroupWorkspace: 'Workspace',
    navGroupProtection: 'Protection',
    navGroupAdmin: 'Administration',
    storageMeter: 'Storage',
    of: 'of',
    collapseSidebar: 'Collapse sidebar',
    expandSidebar: 'Expand sidebar',
    signOut: 'Sign out',

    // top bar
    searchPlaceholder: 'Search files, people, actions…',
    searchDashboardPlaceholder: 'Search AEGIS Drive…',
    searchFilesPlaceholder: 'Search files and folders…',
    searchUploadsPlaceholder: 'Search uploads and actions…',
    searchSharesPlaceholder: 'Search shares and files…',
    searchVersionsPlaceholder: 'Search files or versions…',
    searchStoragePlaceholder: 'Search storage and backup…',
    searchAuditPlaceholder: 'Search events, users, IPs, or resources…',
    searchPeoplePlaceholder: 'Search users…',
    searchSettingsPlaceholder: 'Search settings and actions…',
    searchSecRecent: 'Recent',
    searchSecSuggested: 'Suggested',
    searchSecFiles: 'Files',
    searchSecPeople: 'People',
    searchSecActions: 'Actions',
    searchNoRecent: 'No recent files',
    searchNoResults: 'No results for “{q}”',
    searchNoResultsHint: 'Check the spelling, or try a file name, a person, or a screen name.',
    searchJumpTo: 'Jump to screen',
    searchUnavailable: 'Search unavailable — Private Vault is encrypted',
    // ทูลทิปของช่องค้นหาที่ถูกปิดในจอ Vault — อธิบาย "ทำไม" ไม่ใช่แค่ "ไม่ได้"
    searchUnavailableVault: 'Search is unavailable in the Private Vault — its contents are zero-knowledge encrypted',
    edgeNodeOnline: 'EDGE NODE · ONLINE',
    notifications: 'Notifications',
    previewAs: 'PREVIEW',
    previewAsTooltip: 'Developer preview — swaps the mock server-issued role. Not part of authentication.',

    // dashboard
    dashTitle: 'Dashboard',
    quickActions: 'Quick actions',
    quickUploadLabel: 'Upload',
    quickShareLabel: 'Share',
    quickVaultLabel: 'Vault',
    uploadFile: 'Upload file',
    uploadFileHint: 'Upload directly to the current folder',
    createShareLink: 'Create share link',
    createShareLinkHint: 'Set expiry and access policy',
    openPrivateVault: 'Open Private Vault',
    openPrivateVaultHint: 'Open the encrypted workspace',
    preferencesSaving: 'Saving preferences…',
    preferencesSaveFailed: 'Could not save preferences. Your choice is active for this session only.',
    statStorage: 'Storage Used',
    statFiles: 'Total Files',
    statSessions: 'Active sessions',
    statAlerts: 'Integrity alerts (24h)',
    vsLastWeek: 'vs last week',
    allClear: 'All clear',
    lakeHealth: 'Data Lake Health',
    lakeSubtitle: 'Three tiers · measured status only',
    serverTelemetry: 'Server Telemetry',
    serverTelemetrySub: 'Host metrics · UI contract prepared for a future source',
    telemetryCpu: 'CPU',
    telemetryRam: 'RAM',
    telemetryDisk: 'Disk',
    telemetryNetwork: 'Network',
    telemetryTwingate: 'Twingate',
    telemetryUptime: 'System uptime',
    telemetryUsage: 'Usage',
    telemetryValueUnavailable: 'No data',
    telemetryNoSource: 'No telemetry source connected',
    telemetryStateLoading: 'Loading',
    telemetryStateNormal: 'Normal',
    telemetryStateWarning: 'Warning',
    telemetryStateCritical: 'Critical',
    telemetryStateUnavailable: 'Unavailable',
    tierApp: 'APPLICATION LAYER',
    tierMeta: 'METADATA LAYER',
    tierStorage: 'STORAGE LAYER',
    tierHealthy: 'HEALTHY',
    tierDegraded: 'DEGRADED',
    tierDown: 'DOWN',
    latencyUnavailable: 'No data',
    latency: 'latency',
    activity: 'Activity',
    storageBreakdown: 'Storage breakdown',
    activityTitle: 'Activity',
    activitySub: 'Successful uploads and downloads per day, counted from the audit log.',
    activityEmpty: 'No activity in the last 7 days',
    activityEmptyHint: 'Uploads and downloads appear here as they happen.',
    recentFiles: 'Recent files',
    ofTotal: 'of',
    storageBreakdownSub: 'What this application is storing, by kind.',
    storageBreakdownFree: 'Free on this volume:',
    uploads: 'Uploads',
    downloads: 'Downloads',
    projected: 'projected',

    // files
    filesTitle: 'Files',
    upload: 'Upload',
    newFolder: 'New folder',
    gridView: 'Grid view',
    listView: 'List view',
    sortBy: 'Sort',
    sortName: 'Name',
    sortSize: 'Size',
    sortModified: 'Modified',
    colName: 'NAME',
    colSize: 'SIZE',
    colType: 'TYPE',
    colModified: 'MODIFIED',
    colEncryption: 'STORAGE PROTECTION',
    encServer: 'Data Lake · not encrypted at rest',
    encVault: 'Vault ciphertext',
    selected: 'selected',
    download: 'Download',
    move: 'Move',
    delete: 'Delete',
    rename: 'Rename',
    createLink: 'Create secure link',
    createSecureShare: 'Create Secure Share',
    viewHistory: 'View history',
    filter: 'Filter',
    allFileTypes: 'All file types',
    filesDropHint: 'Drop files anywhere in this workspace to upload to the current folder',
    emptyNoFilesFiltered: 'No files match this search or filter',
    verifySha: 'Verify SHA-256',
    viewMetadata: 'View metadata',
    fileDetails: 'File details',
    size: 'Size',
    type: 'Type',
    uploader: 'Uploader',
    uploadedAt: 'Uploaded at',
    storagePath: 'Storage path',
    integrity: 'Integrity',
    integrityOk: 'VERIFIED',
    integrityPending: 'NOT VERIFIED YET',
    integrityFail: 'MISMATCH',
    verifyChecksum: 'VERIFY CHECKSUM',
    verifying: 'VERIFYING…',
    integrityVerified: '✓ INTEGRITY VERIFIED',
    integrityMismatch: '✕ CHECKSUM MISMATCH',
    verifyUnavailable: 'Verification is unavailable because the stored bytes cannot be read.',
    verifyUnavailableVault: 'Server verification is unavailable for Vault plaintext. Decryption and AES-GCM authentication happen only in your browser.',
    copyHash: 'Copy hash',
    close: 'Close',

    // vault
    vaultTitle: 'Private Vault',
    vaultWarning: 'ZERO-KNOWLEDGE ENCRYPTION · KEY LOSS IS UNRECOVERABLE',
    vaultCipherCaption: 'CIPHERTEXT · NOT READABLE BY SERVER',
    vaultLocked: 'Vault locked',
    vaultUnlocked: 'Vault unlocked',
    unlockVault: 'Unlock vault',
    lockVault: 'Lock vault',
    decrypt: 'Decrypt',
    vaultKeyLabel: 'Vault key',
    vaultKeyNote: 'Your key decrypts files in this browser only. It is never sent to the server — the server stores ciphertext it cannot read.',
    vaultNoSearch: 'No thumbnails. No content search. That is the point.',
    vaultWrongKey: 'Decryption failed — that key does not open this vault.',
    // คนละเรื่องกับกุญแจผิด: เครื่องมือเข้ารหัสในเบราว์เซอร์ทำงานไม่ได้เลย
    vaultUnlockUnavailable: 'Cannot run the decryption engine in this browser — your key was never checked. Reload the page; if this persists, the page may be blocked from running WebAssembly.',
    vaultSetupTitle: 'Create your vault key',
    vaultSetupIntro: 'This key is separate from your account password. It is created in this browser and never sent to AEGIS.',
    vaultSetupCreate: 'Create vault',
    vaultSetupNeeded: 'No vault yet',
    vaultSetupCta: 'Set up vault',
    vaultKeyConfirmLabel: 'Repeat vault key',
    vaultKeyMismatch: 'The two entries do not match.',
    vaultKeyTooShort: 'Use at least 12 characters. This key is the only thing standing between an attacker and your files.',
    vaultSetupAck: 'I understand that if I lose this key, these files are gone forever. AEGIS cannot reset it.',
    vaultDeriving: 'Deriving key…',
    vaultDecrypting: 'Decrypting…',
    vaultDownload: 'Download',
    vaultAutoLocked: 'Vault re-locked after 10 minutes of inactivity.',
    vaultUnnamed: 'Unreadable entry',
    vaultSecurityBanner: 'AES-256-GCM · Zero-Knowledge · encryption and decryption happen in this browser',
    emptyVault: 'No files in the private vault yet',
    encryptFirstFile: 'Encrypt your first file',

    // uploads
    uploadsTitle: 'Uploads',
    uploadFiles: 'Upload files',
    uploadQueue: 'Upload queue',
    uploadNeedsAttention: 'Upload needs attention',
    uploadSuccessTitle: 'Upload complete',
    uploadSuccessBody: '{name} was uploaded successfully.',
    destinationFolder: 'Destination folder',
    currentFolder: 'Current folder',
    uploadWaiting: 'Waiting',
    uploadProcessing: 'Processing',
    uploadComplete: 'Complete',
    uploadFailed: 'Failed',
    uploadCancelled: 'Cancelled',
    cancelAll: 'Cancel all',
    dismiss: 'Dismiss',
    closeUpload: 'Close upload panel',
    chooseFiles: 'Choose files',
    dropHere: 'Drop files here, or click to browse',
    dropSub: 'Stored in the Data Lake · encryption at rest is not configured',
    stStaged: 'STAGED',
    stEncrypting: 'ENCRYPTING',
    stTransferring: 'TRANSFERRING',
    stHashing: 'HASHING',
    stIndexed: 'INDEXED',
    recentUploads: 'Recent uploads',
    simulateUpload: 'Simulate incoming files',

    // shares
    sharesTitle: 'Secure Shares',
    newShare: 'New share link',
    shareFile: 'File',
    expiry: 'Expiry',
    authMethod: 'Auth',
    authPassword: 'Password',
    authOtc: 'One-time code',
    authNone: 'None',
    networkScope: 'NETWORK SCOPE',
    scopeVlan: 'Company VLAN only',
    scopeSubnet: 'Specific subnet',
    scopeAny: 'Any AEGIS-reachable network',
    newShareSub: 'Recipients must already be able to reach AEGIS. Public Internet sharing is not currently available.',
    scopeZones: 'Approved networks',
    scopeZonesTitle: 'Restricted to approved networks',
    scopeZonesBody: 'The link works only when the source address visible to AEGIS is within a network range your administrator defined. Twingate recipients may appear through the connector-visible address.',
    scopeEnforcementNote: 'Application CIDR enforcement is defense in depth; it is not a substitute for Twingate access or device policy.',
    scopeAnyTitle: 'Any AEGIS-reachable network',
    scopeAnyBody: 'Anyone with the link can download from a network that can already reach AEGIS. Public Internet sharing is not currently available.',
    scopeNoZones: 'No network ranges are defined yet, so a restricted link cannot be created. An administrator adds them under Settings, Administration, Network zones.',
    chipZoneRestricted: 'APPROVED NETS',
    linkPassword: 'Link password',
    linkPasswordPlaceholder: 'At least 8 characters',
    linkPasswordHint: 'The recipient is asked for this before the file is sent. Give it to them separately from the link — sending both together defeats the point.',
    linkPasswordTooShort: 'Use at least 8 characters.',
    shareLinkReady: 'Link created',
    copyLink: 'Copy link',
    shareLinkOnceWarn: 'Copy it now. Only a hash of the link is stored, so it cannot be shown again — if you lose it, revoke this link and create another.',
    shareLinkPasswordNote: 'The recipient will be asked for the password you just set.',
    shareLinkScopeNote: 'Only reachable from:',
    createShare: 'Create link',
    activeLinks: 'Active Shares',
    colScope: 'SCOPE',
    colAuth: 'AUTH',
    colExpiresIn: 'EXPIRES IN',
    colCreatedBy: 'CREATED BY',
    colHits: 'HITS',
    revoke: 'Revoke',
    revokeTitle: 'Revoke share link?',
    revokeBody: 'The link for “{name}” dies immediately. Anyone holding it gets nothing. This cannot be undone.',
    confirmRevoke: 'Revoke permanently',
    cancel: 'Cancel',
    expired: 'EXPIRED',
    chipVlanOnly: 'VLAN ONLY',
    chipSubnet: 'SUBNET',
    chipAnyNetwork: 'AEGIS-REACHABLE',

    // snapshots
    current: 'CURRENT',
    colTimestamp: 'TIMESTAMP',

    // storage
    storageTitle: 'Storage & Backup',
    capacity: 'Capacity',
    degraded: 'DEGRADED',
    colStatus: 'STATUS',
    docs: 'Documents',
    media: 'Media',
    archives: 'Archives',
    vaultSeg: 'Vault',
    free: 'Free',
    storageZeroGb: '0 GB',
    backupTarget: 'Backup target',
    backupSchedule: 'Schedule',
    backupScheduleEmpty: 'No automatic backup schedule has been configured',
    setupNow: 'Set up now',

    // audit
    auditTitle: 'Audit Log',
    auditSubtitle: 'Append-only. Nothing here can be edited.',
    colActor: 'ACTOR',
    colAction: 'ACTION',
    colTargetA: 'TARGET',
    colResult: 'RESULT',
    colSourceIp: 'SOURCE IP',
    exportCsv: 'Export CSV',
    filterAll: 'All',
    filterDenied: 'Denied only',
    filterActor: 'Actor',
    filterAction: 'Action',
    filterRange: 'Date range',
    filterScope: 'Scope',
    filterStatus: 'Status',
    filterActive: 'Active',
    filterExpiresWithin: 'Expires within',
    emptyNoAuditFiltered: 'No events match these filters',
    emptyNoSharesFiltered: 'No links match these filters',
    resOk: 'OK',
    resDenied: 'DENIED',
    resBlocked: 'BLOCKED',

    // access
    accessTitle: 'Access Control',
    addUser: 'Add user',
    accessFilter: 'Filter by name or username…',
    accessFilterNone: 'No users match “{q}”',
    colUser: 'USER',
    colRole: 'ROLE',
    colLastLogin: 'LAST LOGIN',
    active: 'ACTIVE',
    accountReady: 'ACCOUNT READY',
    suspended: 'SUSPENDED',
    pendingReset: 'PENDING RESET',
    accessAssignedName: 'Assigned name',
    pendingResetHint: 'Still on a temporary password — blocked from every screen until it is changed.',
    neverLoggedIn: 'Never',
    tempPasswordIntro: 'Account created. Copy this temporary password and hand it to the user out-of-band (e.g. in person or a secure chat) — it will not be shown again.',
    tempPasswordLabel: 'Temporary password',
    copyTempPassword: 'Copy temporary password',
    copied: 'Copied',
    tempPasswordWarn: 'The user must reset this password on their first login before they can use anything else.',
    done: 'Done',
    permMatrix: 'Role Permission Reference',
    permUploadDl: 'Upload / download files',
    permShare: 'Create share links',
    permVault: 'Private Vault',
    permSnapRestore: 'Restore earlier file versions',
    permAudit: 'Read audit log',
    permManageUsers: 'Manage users & roles',
    firewallNote: 'Firewall-zone changes require elevated OS privileges on the edge node — they are managed there, not here.',
    roleAdmin: 'Admin',
    roleUser: 'DataLake-User',
    currentDeviceSession: '1 · this device',
    sessionsThisInstance: 'Sessions (this instance)',
    sessionCount: '{n}',
    sessionCountCurrent: '{n} · includes this device',
    noOtherUsers: 'No other users are in the system yet',

    // settings
    settingsTitle: 'Settings',
    setAppearance: 'Appearance',
    setAccount: 'Account',
    setSecurity: 'Security & Privacy',
    setStorageData: 'Storage & Data',
    setAdmin: 'Administrator',
    theme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    language: 'Language',
    density: 'Display density',
    densityComfortable: 'Comfortable',
    densityCompact: 'Compact',
    profile: 'Profile',
    changePassword: 'Change password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    updatePassword: 'Update password',
    mandatoryResetTitle: 'Secure your account before continuing',
    mandatoryResetSubtitle: 'This account is still using a temporary password. Change it before accessing any Drive data.',
    temporaryPassword: 'Current temporary password',
    confirmNewPassword: 'Confirm new password',
    mandatoryResetSecurityNote: 'Your password stays in memory only and is never saved in browser storage.',
    pwConfirmMismatch: 'The new passwords do not match.',
    activeSessions: 'Active sessions',
    thisDevice: 'THIS DEVICE',
    lastActive: 'Last active',
    emptyNoSessions: 'No active sessions',
    emptyNoSessionsHint: 'Sessions from signed-in devices will appear here.',
    vaultKeyMgmt: 'Private Vault key',
    vaultKeyMgmtNote: 'The vault key exists only on your devices. AEGIS cannot reset it. If it is lost, vault contents are lost with it.',
    shareDefaults: 'Share link defaults',
    encAtRest: 'Encryption at rest',
    encAtRestVault: 'Private Vault files are encrypted in your browser before upload — the server only ever holds ciphertext it cannot read, and there is no server-side key involved.',
    encAtRestTodo: 'Ordinary Data Lake uploads are stored unencrypted on disk. There is no server-side master key in this system, so there is nothing to rotate. Implementing this needs encryption in the storage layer plus a decision on where key material lives.',
    notImplemented: 'Not yet implemented',
    designIntent: 'DESIGN INTENT',
    remoteAccessDocNote: 'Twingate design reference only — connector telemetry is not connected yet.',
    zonesNote: 'A record of intent, not a control. Enforcement happens at the host firewall (UFW/VLAN); adding a zone here changes nothing in the app.',
    shareDefaultsTodo: 'Per-user share defaults are not stored yet, so the new-link form always starts from the same values.',
    snapScheduleTodo: 'Scheduling needs a snapshot mechanism that this deployment cannot provide — see File history for what is available instead.',
    backupTargetsTodo: 'No backup job or destination is configured in this deployment.',
    vaultRecoveryTitle: 'Vault Recovery Phrase (Mnemonic)',
    vaultRecoveryNotConnected: 'Not yet generated. Recovery is not connected to the current zero-knowledge vault, so no phrase is fabricated.',
    vaultRecoveryUnavailable: 'A real recovery phrase requires BIP-39 entropy and integration with vault key derivation.',
    generateRecoveryPhrase: 'Generate 12-word recovery phrase',
    remoteAccessTitle: 'Remote Access & Devices',
    remoteInactive: 'Inactive',
    remoteLeastPrivilege: 'Least-privilege access · mobile / off-site',
    remoteConnectorStatus: 'Connector status',
    remoteReachableResource: 'Reachable resource',
    remoteInactiveHint: 'No connector telemetry is connected yet. This neutral state does not claim the channel is online.',
    profileName: 'Display name',
    profileNameHint: 'Shown across the app instead of the name your administrator set. Your username never changes and is always shown next to it. Leave empty to go back to the administrator name.',
    profileAccountName: 'Administrator-assigned name',
    saveProfile: 'Save',
    saving: 'Saving…',
    saved: 'Saved',
    avatarUpload: 'Upload picture',
    avatarRemove: 'Remove',
    avatarHint: 'PNG or JPEG, up to 2 MB. Location and camera metadata are stripped before the file is stored.',
    avatarTooLarge: 'That image is larger than 2 MB.',
    avatarUnsupported: 'Only PNG and JPEG images are accepted.',
    revokeSession: 'Sign out',
    sessionsVolatileNote: 'Sessions live in server memory — restarting the server signs every device out.',
    deviceUnknown: 'Unknown device',
    pwPolicyHint: 'At least 12 characters, and not the same as your current password or username.',
    pwUpdated: 'Password updated',
    pwWeak: 'That password does not meet the policy.',
    pwWrongCurrent: 'Current password is incorrect.',
    networkZones: 'Network zones',
    emptyNoZones: 'No network zones defined',
    zoneName: 'Zone name',
    zoneCidr: 'CIDR',
    addZone: 'Add zone',
    removeZone: 'Remove',
    zoneNamePlaceholder: 'e.g. R&D VLAN',
    zoneCidrPlaceholder: 'e.g. 10.20.0.0/24',
    invalidZone: 'Enter a name and a valid CIDR (e.g. 10.20.0.0/24)',
    backupTargets: 'Backup targets',
    hour1: '1 hour',
    hours24: '24 hours',
    days7: '7 days',
    days30: '30 days',

    // misc
    justNow: 'just now',
    minAgo: '{n}m ago',
    hourAgo: '{n}h ago',
    dayAgo: '{n}d ago',
    empty: 'Nothing here yet',
  },

  th: {
    productName: 'AEGIS Drive_LC',
    productTag: 'AUTONOMOUS EDGE-GUARD INFRASTRUCTURE SYSTEM',
    productLockupSub: 'พื้นที่จัดเก็บระดับองค์กร · ศูนย์ควบคุมความปลอดภัย',
    breadcrumb: 'เส้นทางนำทาง',
    moreActions: 'การดำเนินการเพิ่มเติม',
    errorBoundaryTitle: 'เกิดข้อผิดพลาดที่ไม่คาดคิด',
    errorBoundaryBody: 'ไม่สามารถแสดงหน้านี้ได้ รายละเอียดทางเทคนิคถูกบันทึกไว้ในคอนโซลของเบราว์เซอร์',
    errorBoundaryReload: 'โหลดใหม่',

    loginTitle: 'เข้าสู่ระบบ',
    loginSubtitle: 'NAS ปลอดภัย · ติดตั้งภายในองค์กร',
    username: 'ชื่อผู้ใช้',
    password: 'รหัสผ่าน',
    usernamePlaceholder: 'ชื่อ.นามสกุล',
    passwordPlaceholder: '••••••••',
    showPassword: 'แสดงรหัสผ่าน',
    hidePassword: 'ซ่อนรหัสผ่าน',
    rememberSession: 'จดจำเซสชันนี้',
    signIn: 'เข้าสู่ระบบ',
    signingIn: 'กำลังตรวจสอบ…',
    loginFailed: 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง',
    lockout: 'พยายามหลายครั้งเกินไป — ล็อก {s} วินาที',
    loginBlockedCsrf: 'คำขอถูกปฏิเสธ — ต้นทางไม่ตรงกัน กรุณาโหลดหน้าใหม่แล้วลองอีกครั้ง',
    loginNetwork: 'ติดต่อเซิร์ฟเวอร์ไม่ได้ ตรวจการเชื่อมต่อแล้วลองอีกครั้ง',
    loginTimeout: 'เซิร์ฟเวอร์ตอบกลับช้าเกินไป กรุณาลองอีกครั้ง',
    loginServerError: 'เซิร์ฟเวอร์ขัดข้อง — ยังไม่มีการตรวจรหัสผ่าน กรุณาลองอีกครั้ง',

    // สี่สถานะของจอ (loading = skeleton ไม่ต้องมีข้อความ)
    errLoadTitle: 'โหลดหน้านี้ไม่สำเร็จ',
    errLoadHint: 'เซิร์ฟเวอร์ Drive ไม่ตอบสนอง — ตรวจสอบว่าเซิร์ฟเวอร์กำลังทำงาน แล้วลองอีกครั้ง',
    errLoadTimeout: 'คำขอหมดเวลา — Edge node อาจกำลังโหลดหนัก ลองอีกครั้ง',
    retry: 'ลองใหม่',
    emptyNoFiles: 'ยังไม่มีไฟล์',
    emptyFolder: 'ยังไม่มีไฟล์หรือโฟลเดอร์ในตำแหน่งนี้',
    createFirstFolder: 'สร้างโฟลเดอร์แรกของคุณ',
    emptyNoFilesHint: 'อัปโหลดไฟล์หรือสร้างโฟลเดอร์เพื่อเริ่มต้น',
    dependencyUnavailableHint: 'ยังไม่ได้เชื่อมต่อบริการ Metadata ข้อมูลจึงไม่พร้อมใช้งานในขณะนี้ ไม่ได้หมายความว่าข้อมูลถูกลบ',
    dashboardUnavailable: 'ข้อมูล Dashboard ไม่พร้อมใช้งาน',
    filesUnavailable: 'ไม่สามารถโหลดไฟล์ได้',
    sharesUnavailable: 'Secure Shares ไม่พร้อมใช้งาน',
    historyUnavailable: 'ประวัติไฟล์ไม่พร้อมใช้งาน',
    auditUnavailable: 'Audit Log ไม่พร้อมใช้งาน',
    accessUnavailable: 'Access Control ไม่พร้อมใช้งาน',
    emptyNoShares: 'ยังไม่มีลิงก์แชร์ที่ใช้งานอยู่',
    emptyNoSharesHint: 'สร้างลิงก์ทางซ้าย — ทุกลิงก์มีวันหมดอายุและขอบเขตเครือข่ายกำกับ',
    emptyNoAudit: 'ยังไม่มีบันทึกกิจกรรม',
    emptyNoAuditHint: 'การกระทำที่เกี่ยวข้องกับความปลอดภัยจะถูกบันทึกที่นี่',
    emptyNoUsers: 'ยังไม่มีบัญชีผู้ใช้',
    emptyNoActivity: 'ยังไม่มีกิจกรรมล่าสุด',
    emptyNoLoginHistory: 'ยังไม่มีประวัติการเข้าสู่ระบบ',
    emptyNoRecentFiles: 'ยังไม่มีไฟล์ล่าสุด',
    notConnected: 'ยังไม่เชื่อมต่อ',
    driveOnline: 'Drive: ออนไลน์',
    driveNotConnected: 'Drive: ยังไม่เชื่อมต่อ',
    metadataNotConnected: 'Metadata: ยังไม่เชื่อมต่อ',
    metadataConnected: 'Metadata: {source}',
    emptyNoUploads: 'ยังไม่มีการอัปโหลดล่าสุด',
    emptyNoUploadsHint: 'ลากไฟล์มาวางด้านบนเพื่ออัปโหลดไปยังโฟลเดอร์ปัจจุบัน',
    dashLoginHistory: 'ประวัติการเข้าสู่ระบบ',
    dashLoginHistorySub: 'การเข้าสู่ระบบล่าสุดของคุณ — สถานะความปลอดภัยส่วนตัว',
    statSecurity: 'เหตุการณ์ DENIED/BLOCKED (100 รายการล่าสุด)',
    stFailed: 'ไม่สำเร็จ',
    uploadTooLarge: 'ใหญ่กว่าเพดานอัปโหลด 1 GB — ไฟล์นี้ไม่ได้ถูกส่งไป',
    confirmDeleteTitle: 'ลบออกจาก data lake?',
    confirmDeleteBody: '“{name}” และประวัติเวอร์ชันทั้งหมดของมันจะถูกลบอย่างถาวร ไม่มีถังขยะและไม่มีอะไรกู้คืนให้ได้',
    actionFailed: 'ดำเนินการไม่สำเร็จ — เซิร์ฟเวอร์ไม่รับคำขอ ลองอีกครั้ง',
    layerNetwork: 'LAYER 0 · NETWORK',
    layerNetworkDesc: 'VPN + VLAN',
    layerApp: 'LAYER 1 · APPLICATION',
    layerAppDesc: 'ข้อมูลประจำตัว',
    layerStorage: 'LAYER 2 · STORAGE',
    layerStorageDesc: 'Data Lake · ยังไม่เข้ารหัสขณะจัดเก็บ',
    layerMeta: 'LAYER 3 · METADATA',
    layerMetaDesc: 'PostgreSQL',

    navDashboard: 'แดชบอร์ด',
    navFiles: 'ไฟล์',
    navVault: 'ห้องนิรภัยส่วนตัว',
    navUploads: 'อัปโหลด',
    navShares: 'ลิงก์แชร์ปลอดภัย',
    navVersions: 'ประวัติไฟล์',
    versionsTitle: 'ประวัติไฟล์',
    versionsMyFiles: 'ไฟล์ของคุณ',
    versionsNone: 'ยังไม่มีเวอร์ชันก่อนหน้า',
    versionsCount: 'มี {n} เวอร์ชันก่อนหน้า',
    versionsEmptyHint: 'อัปโหลดไฟล์ชื่อเดิมอีกครั้ง แล้วเวอร์ชันที่ถูกแทนจะถูกเก็บไว้ที่นี่',
    versionsPickFile: 'เลือกไฟล์เพื่อดูประวัติของมัน',
    versionCurrent: 'ปัจจุบัน',
    versionSupersededBy: 'ถูกแทนโดย',
    versionRestore: 'กู้คืน',
    versionRestoring: 'กำลังกู้คืน…',
    versionRestored: 'กู้คืนแล้ว ไฟล์ที่เคยเป็นปัจจุบันกลายเป็นเวอร์ชันก่อนหน้าล่าสุด',
    versionRestoreTitle: 'กู้คืนเวอร์ชันนี้?',
    versionRestoreBody: 'เวอร์ชันจาก {when} จะกลายเป็นไฟล์ปัจจุบัน',
    versionRestoreSafe: 'ไม่มีอะไรสูญหาย — ไฟล์ที่เป็นปัจจุบันอยู่ตอนนี้จะถูกเก็บเป็นเวอร์ชันก่อนหน้า จึงย้อนกลับได้',
    versionsScopeTitle: 'นี่คือประวัติ "ต่อไฟล์" ไม่ใช่สแนปช็อตของ Data Lake ทั้งชั้น',
    versionsScopeBody: 'สแนปช็อตแบบ point-in-time ต้องใช้ระบบไฟล์ที่รองรับ (LVM, ZFS หรือ Btrfs) ส่วน deployment นี้เก็บไฟล์บน volume ธรรมดา ไฟล์ที่ถูกลบไปแล้วไม่มีประวัติให้กู้ และเวอร์ชันเหล่านี้อยู่บนดิสก์ลูกเดียวกับตัวไฟล์ — ดิสก์เสียก็หายไปด้วย นั่นเป็นหน้าที่ของการสำรองข้อมูลนอกเครื่อง ซึ่งยังไม่ได้ตั้งค่าไว้',
    versionsTrackEmpty: 'ยังไม่มีประวัติเวอร์ชันที่บันทึกไว้ — เวอร์ชันก่อนหน้าจะปรากฏเมื่อมีการแทนที่ไฟล์',
    versionsNoFiles: 'ยังไม่มีไฟล์สำหรับแสดงประวัติเวอร์ชัน',
    notAvailable: 'ยังไม่มีข้อมูลที่นี่',
    notConfigured: 'ยังไม่ได้ตั้งค่า',
    capacitySub: 'อ่านจากระบบไฟล์ที่ Data Lake อยู่',
    capacityTotal: 'ความจุรวม',
    capacityUsed: 'ใช้ไป',
    capacityUsedPct: 'ใช้ไป',
    capacityUnreadable: 'ระบบไฟล์ไม่รายงานความจุกลับมา จึงไม่แสดงตัวเลข ดีกว่าแสดงค่าที่เดาเอา',
    unaccounted: 'อื่น ๆ บน volume นี้',
    unaccountedHint: 'พื้นที่ที่ระบบไฟล์นับว่าใช้ไปแล้วแต่ไม่ได้มาจากแอปนี้ — ไฟล์ของระบบ, คอนเทนเนอร์อื่นที่ใช้ volume ร่วมกัน หรือข้อมูลกำพร้า',
    versions: 'เวอร์ชันก่อนหน้า',
    other: 'ไฟล์อื่น ๆ',
    diskHealth: 'สถานะดิสก์',
    diskHealthWhy: 'รุ่น หมายเลขเครื่อง อุณหภูมิ และสถานะ SMART ต้องเข้าถึง raw device (smartctl ที่ต้องมี CAP_SYS_RAWIO) คอนเทนเนอร์นี้รันแบบไม่มีสิทธิ์พิเศษด้วย user ที่ไม่ใช่ root และไม่ได้รับสิทธิ์นั้น จึงไม่แสดงตัวเลขใด การรายงานค่าเหล่านี้ต้องเปลี่ยนที่ระดับโฮสต์ ไม่ใช่เขียนโค้ดเพิ่ม',
    raidStatus: 'RAID',
    raidWhy: 'deployment นี้ไม่มี array ที่ตั้งค่าไว้ และการอ่านสถานะ array ต้องใช้ /proc/mdstat ของโฮสต์',
    backupJobs: 'งานสำรองข้อมูล',
    backupJobsWhy: 'ยังไม่มีงานสำรองข้อมูลหรือปลายทางใดถูกตั้งค่าไว้ที่ไหนใน deployment นี้ จนกว่าจะมี ข้อมูลจะไม่ถูกคัดลอกออกจากเครื่องนี้เลย',
    navStorage: 'พื้นที่เก็บ & สำรอง',
    navAudit: 'บันทึกตรวจสอบ',
    navAccess: 'ควบคุมสิทธิ์',
    navSettings: 'ตั้งค่า',
    navGroupWorkspace: 'พื้นที่ทำงาน',
    navGroupProtection: 'การปกป้อง',
    navGroupAdmin: 'ผู้ดูแลระบบ',
    storageMeter: 'พื้นที่เก็บ',
    of: 'จาก',
    collapseSidebar: 'ย่อแถบข้าง',
    expandSidebar: 'ขยายแถบข้าง',
    signOut: 'ออกจากระบบ',

    searchPlaceholder: 'ค้นหาไฟล์ ผู้คน การทำงาน…',
    searchDashboardPlaceholder: 'ค้นหาใน AEGIS Drive…',
    searchFilesPlaceholder: 'ค้นหาไฟล์และโฟลเดอร์…',
    searchUploadsPlaceholder: 'ค้นหาการอัปโหลดและคำสั่ง…',
    searchSharesPlaceholder: 'ค้นหาลิงก์แชร์และไฟล์…',
    searchVersionsPlaceholder: 'ค้นหาไฟล์หรือเวอร์ชัน…',
    searchStoragePlaceholder: 'ค้นหาพื้นที่เก็บและการสำรอง…',
    searchAuditPlaceholder: 'ค้นหาเหตุการณ์ ผู้ใช้ IP หรือทรัพยากร…',
    searchPeoplePlaceholder: 'ค้นหาผู้ใช้…',
    searchSettingsPlaceholder: 'ค้นหาการตั้งค่าและคำสั่ง…',
    searchSecRecent: 'ล่าสุด',
    searchSecSuggested: 'แนะนำ',
    searchSecFiles: 'ไฟล์',
    searchSecPeople: 'ผู้คน',
    searchSecActions: 'การทำงาน',
    searchNoRecent: 'ยังไม่มีไฟล์ล่าสุด',
    searchNoResults: 'ไม่พบผลลัพธ์สำหรับ “{q}”',
    searchNoResultsHint: 'ลองตรวจตัวสะกด หรือค้นด้วยชื่อไฟล์ ชื่อผู้ใช้ หรือชื่อหน้าจอ',
    searchJumpTo: 'ไปที่หน้านี้',
    searchUnavailable: 'ค้นหาไม่ได้ — ห้องนิรภัยส่วนตัวถูกเข้ารหัส',
    searchUnavailableVault: 'ค้นหาไม่พร้อมใช้งานในห้องนิรภัย — เนื้อหาถูกเข้ารหัสแบบ zero-knowledge',
    edgeNodeOnline: 'EDGE NODE · ออนไลน์',
    notifications: 'การแจ้งเตือน',
    previewAs: 'พรีวิว',
    previewAsTooltip: 'เครื่องมือสำหรับนักพัฒนา — สลับ role จำลองที่เซิร์ฟเวอร์ออกให้ ไม่ใช่ส่วนหนึ่งของการยืนยันตัวตน',

    dashTitle: 'แดชบอร์ด',
    quickActions: 'คำสั่งด่วน',
    quickUploadLabel: 'อัปโหลด',
    quickShareLabel: 'แชร์',
    quickVaultLabel: 'ห้องนิรภัย',
    uploadFile: 'อัปโหลดไฟล์',
    uploadFileHint: 'อัปโหลดไปยังโฟลเดอร์ปัจจุบันโดยตรง',
    createShareLink: 'สร้างลิงก์แชร์',
    createShareLinkHint: 'กำหนดวันหมดอายุและนโยบายการเข้าถึง',
    openPrivateVault: 'เปิดห้องนิรภัยส่วนตัว',
    openPrivateVaultHint: 'เปิดพื้นที่ทำงานที่เข้ารหัส',
    preferencesSaving: 'กำลังบันทึกการตั้งค่า…',
    preferencesSaveFailed: 'บันทึกการตั้งค่าไม่สำเร็จ ค่าที่เลือกใช้ได้เฉพาะในเซสชันนี้',
    statStorage: 'พื้นที่จัดเก็บที่ใช้ไป',
    statFiles: 'ไฟล์ทั้งหมด',
    statSessions: 'เซสชันที่ใช้งาน',
    statAlerts: 'แจ้งเตือนความสมบูรณ์ (24 ชม.)',
    vsLastWeek: 'เทียบสัปดาห์ก่อน',
    allClear: 'ปกติทั้งหมด',
    lakeHealth: 'สถานะระบบ Data Lake',
    lakeSubtitle: 'สามชั้น · แสดงเฉพาะสถานะที่ตรวจวัดได้',
    serverTelemetry: 'ข้อมูลสถานะเซิร์ฟเวอร์',
    serverTelemetrySub: 'ค่าระดับเครื่อง · เตรียม UI สำหรับแหล่งข้อมูลจริงในอนาคต',
    telemetryCpu: 'CPU',
    telemetryRam: 'RAM',
    telemetryDisk: 'ดิสก์',
    telemetryNetwork: 'เครือข่าย',
    telemetryTwingate: 'Twingate',
    telemetryUptime: 'ระยะเวลาทำงานของระบบ',
    telemetryUsage: 'การใช้งาน',
    telemetryValueUnavailable: 'ไม่มีข้อมูล',
    telemetryNoSource: 'ยังไม่ได้เชื่อมต่อแหล่งข้อมูล Telemetry',
    telemetryStateLoading: 'กำลังโหลด',
    telemetryStateNormal: 'ปกติ',
    telemetryStateWarning: 'เตือน',
    telemetryStateCritical: 'วิกฤต',
    telemetryStateUnavailable: 'ไม่พร้อมใช้งาน',
    tierApp: 'APPLICATION LAYER',
    tierMeta: 'METADATA LAYER',
    tierStorage: 'STORAGE LAYER',
    tierHealthy: 'ปกติ',
    tierDegraded: 'เสื่อมสภาพ',
    tierDown: 'ล่ม',
    latencyUnavailable: 'ไม่มีข้อมูล',
    latency: 'เวลาแฝง',
    activity: 'กิจกรรม',
    storageBreakdown: 'สัดส่วนพื้นที่เก็บ',
    activityTitle: 'กิจกรรม',
    activitySub: 'จำนวนการอัปโหลดและดาวน์โหลดที่สำเร็จต่อวัน นับจาก audit log',
    activityEmpty: 'ไม่มีกิจกรรมใน 7 วันที่ผ่านมา',
    activityEmptyHint: 'การอัปโหลดและดาวน์โหลดจะปรากฏที่นี่เมื่อเกิดขึ้น',
    recentFiles: 'ไฟล์ล่าสุด',
    ofTotal: 'จาก',
    storageBreakdownSub: 'สิ่งที่แอปนี้จัดเก็บ แบ่งตามชนิด',
    storageBreakdownFree: 'พื้นที่ว่างบน volume นี้:',
    uploads: 'อัปโหลด',
    downloads: 'ดาวน์โหลด',
    projected: 'คาดการณ์',

    filesTitle: 'ไฟล์',
    upload: 'อัปโหลด',
    newFolder: 'โฟลเดอร์ใหม่',
    gridView: 'มุมมองตาราง',
    listView: 'มุมมองรายการ',
    sortBy: 'เรียงตาม',
    sortName: 'ชื่อ',
    sortSize: 'ขนาด',
    sortModified: 'แก้ไขล่าสุด',
    colName: 'ชื่อ',
    colSize: 'ขนาด',
    colType: 'ชนิด',
    colModified: 'แก้ไขล่าสุด',
    colEncryption: 'การปกป้องขณะจัดเก็บ',
    encServer: 'Data Lake · ยังไม่เข้ารหัสขณะจัดเก็บ',
    encVault: 'ไซเฟอร์เท็กซ์ห้องนิรภัย',
    selected: 'รายการที่เลือก',
    download: 'ดาวน์โหลด',
    move: 'ย้าย',
    delete: 'ลบ',
    rename: 'เปลี่ยนชื่อ',
    createLink: 'สร้างลิงก์ปลอดภัย',
    createSecureShare: 'สร้างลิงก์แชร์ปลอดภัย',
    viewHistory: 'ดูประวัติไฟล์',
    filter: 'ตัวกรอง',
    allFileTypes: 'ไฟล์ทุกชนิด',
    filesDropHint: 'ลากไฟล์มาวางในพื้นที่นี้เพื่ออัปโหลดไปยังโฟลเดอร์ปัจจุบัน',
    emptyNoFilesFiltered: 'ไม่มีไฟล์ที่ตรงกับการค้นหาหรือตัวกรองนี้',
    verifySha: 'ตรวจสอบ SHA-256',
    viewMetadata: 'ดูเมทาดาทา',
    fileDetails: 'รายละเอียดไฟล์',
    size: 'ขนาด',
    type: 'ชนิด',
    uploader: 'ผู้อัปโหลด',
    uploadedAt: 'อัปโหลดเมื่อ',
    storagePath: 'พาธจัดเก็บ',
    integrity: 'ความสมบูรณ์',
    integrityOk: 'ตรวจสอบแล้ว',
    integrityPending: 'ยังไม่ได้ตรวจสอบ',
    integrityFail: 'ไม่ตรงกัน',
    verifyChecksum: 'ตรวจสอบเช็กซัม',
    verifying: 'กำลังตรวจสอบ…',
    integrityVerified: '✓ ความสมบูรณ์ถูกต้อง',
    integrityMismatch: '✕ เช็กซัมไม่ตรงกัน',
    verifyUnavailable: 'ตรวจสอบไม่ได้ เพราะเซิร์ฟเวอร์อ่านไบต์ที่จัดเก็บไว้ไม่ได้',
    verifyUnavailableVault: 'เซิร์ฟเวอร์ตรวจ plaintext ของ Vault ไม่ได้ การถอดรหัสและตรวจ AES-GCM ทำเฉพาะในเบราว์เซอร์ของคุณ',
    copyHash: 'คัดลอกแฮช',
    close: 'ปิด',

    vaultTitle: 'ห้องนิรภัยส่วนตัว',
    vaultWarning: 'เข้ารหัสแบบ ZERO-KNOWLEDGE · กุญแจหายคือกู้ไม่ได้',
    vaultCipherCaption: 'CIPHERTEXT · เซิร์ฟเวอร์อ่านไม่ได้',
    vaultLocked: 'ล็อกอยู่',
    vaultUnlocked: 'ปลดล็อกแล้ว',
    unlockVault: 'ปลดล็อกห้องนิรภัย',
    lockVault: 'ล็อกห้องนิรภัย',
    decrypt: 'ถอดรหัส',
    vaultKeyLabel: 'กุญแจห้องนิรภัย',
    vaultKeyNote: 'กุญแจถอดรหัสไฟล์ในเบราว์เซอร์นี้เท่านั้น ไม่ถูกส่งไปเซิร์ฟเวอร์ — เซิร์ฟเวอร์เก็บเพียงไซเฟอร์เท็กซ์ที่อ่านไม่ออก',
    vaultNoSearch: 'ไม่มีภาพตัวอย่าง ไม่มีการค้นหาเนื้อหา — นั่นแหละคือประเด็น',
    vaultWrongKey: 'ถอดรหัสไม่สำเร็จ — กุญแจนี้เปิดห้องนิรภัยนี้ไม่ได้',
    vaultUnlockUnavailable: 'เรียกใช้ตัวถอดรหัสในเบราว์เซอร์นี้ไม่ได้ — ยังไม่มีการตรวจกุญแจของคุณเลย ลองโหลดหน้าใหม่ ถ้ายังเป็นอยู่ แสดงว่าหน้านี้ถูกห้ามรัน WebAssembly',
    vaultSetupTitle: 'สร้างกุญแจห้องนิรภัย',
    vaultSetupIntro: 'กุญแจนี้แยกจากรหัสผ่านบัญชีของคุณ ถูกสร้างในเบราว์เซอร์นี้ และไม่ถูกส่งไปยัง AEGIS',
    vaultSetupCreate: 'สร้างห้องนิรภัย',
    vaultSetupNeeded: 'ยังไม่มีห้องนิรภัย',
    vaultSetupCta: 'ตั้งค่าห้องนิรภัย',
    vaultKeyConfirmLabel: 'พิมพ์กุญแจอีกครั้ง',
    vaultKeyMismatch: 'กุญแจสองครั้งไม่ตรงกัน',
    vaultKeyTooShort: 'ใช้อย่างน้อย 12 ตัวอักษร — กุญแจนี้คือสิ่งเดียวที่กั้นระหว่างผู้บุกรุกกับไฟล์ของคุณ',
    vaultSetupAck: 'ฉันเข้าใจว่าถ้าลืมกุญแจนี้ ไฟล์เหล่านี้จะหายถาวร AEGIS รีเซ็ตให้ไม่ได้',
    vaultDeriving: 'กำลังสร้างกุญแจ…',
    vaultDecrypting: 'กำลังถอดรหัส…',
    vaultDownload: 'ดาวน์โหลด',
    vaultAutoLocked: 'ล็อกห้องนิรภัยอัตโนมัติ หลังไม่มีการใช้งาน 10 นาที',
    vaultUnnamed: 'รายการที่อ่านไม่ออก',
    vaultSecurityBanner: 'AES-256-GCM · Zero-Knowledge · เข้ารหัสและถอดรหัสภายในเบราว์เซอร์นี้',
    emptyVault: 'ยังไม่มีไฟล์ในห้องนิรภัย',
    encryptFirstFile: 'เข้ารหัสไฟล์แรกของคุณ',

    uploadsTitle: 'อัปโหลด',
    uploadFiles: 'อัปโหลดไฟล์',
    uploadQueue: 'คิวอัปโหลด',
    uploadNeedsAttention: 'การอัปโหลดต้องตรวจสอบ',
    uploadSuccessTitle: 'อัปโหลดสำเร็จ',
    uploadSuccessBody: 'อัปโหลด {name} สำเร็จแล้ว',
    destinationFolder: 'โฟลเดอร์ปลายทาง',
    currentFolder: 'โฟลเดอร์ปัจจุบัน',
    uploadWaiting: 'กำลังรอ',
    uploadProcessing: 'กำลังประมวลผล',
    uploadComplete: 'เสร็จสมบูรณ์',
    uploadFailed: 'ล้มเหลว',
    uploadCancelled: 'ยกเลิกแล้ว',
    cancelAll: 'ยกเลิกทั้งหมด',
    dismiss: 'ซ่อนรายการ',
    closeUpload: 'ปิดแผงอัปโหลด',
    chooseFiles: 'เลือกไฟล์',
    dropHere: 'ลากและวางไฟล์ที่นี่ หรือคลิกเพื่อเลือก',
    dropSub: 'จัดเก็บใน Data Lake · ยังไม่ได้เปิดใช้การเข้ารหัสขณะจัดเก็บ',
    stStaged: 'เตรียมแล้ว',
    stEncrypting: 'กำลังเข้ารหัส',
    stTransferring: 'กำลังส่ง',
    stHashing: 'กำลังแฮช',
    stIndexed: 'จัดดัชนีแล้ว',
    recentUploads: 'อัปโหลดล่าสุด',
    simulateUpload: 'จำลองไฟล์ขาเข้า',

    sharesTitle: 'ลิงก์แชร์ปลอดภัย',
    newShare: 'สร้างลิงก์แชร์',
    shareFile: 'ไฟล์',
    expiry: 'อายุลิงก์',
    authMethod: 'การยืนยัน',
    authPassword: 'รหัสผ่าน',
    authOtc: 'รหัสใช้ครั้งเดียว',
    authNone: 'ไม่มี',
    networkScope: 'ขอบเขตเครือข่าย',
    scopeVlan: 'เฉพาะ VLAN บริษัท',
    scopeSubnet: 'ซับเน็ตที่กำหนด',
    scopeAny: 'ทุกเครือข่ายที่เข้าถึง AEGIS ได้',
    newShareSub: 'ผู้รับต้องอยู่บนเครือข่ายที่เข้าถึง AEGIS ได้อยู่แล้ว ขณะนี้ยังไม่รองรับการแชร์ผ่านอินเทอร์เน็ตสาธารณะ',
    scopeZones: 'เครือข่ายที่อนุญาต',
    scopeZonesTitle: 'จำกัดเฉพาะเครือข่ายที่อนุญาต',
    scopeZonesBody: 'ลิงก์ใช้ได้เฉพาะเมื่อที่อยู่ต้นทางที่ AEGIS มองเห็นอยู่ในช่วงเครือข่ายที่ผู้ดูแลกำหนด ผู้รับที่เชื่อมต่อผ่าน Twingate อาจปรากฏเป็นที่อยู่ที่ Connector มองเห็น',
    scopeEnforcementNote: 'การบังคับ CIDR ระดับแอปเป็นการป้องกันเสริม ไม่ใช้แทนนโยบายการเข้าถึงของ Twingate หรือนโยบายอุปกรณ์',
    scopeAnyTitle: 'ทุกเครือข่ายที่เข้าถึง AEGIS ได้',
    scopeAnyBody: 'ผู้ที่มีลิงก์ดาวน์โหลดได้จากเครือข่ายที่เข้าถึง AEGIS ได้อยู่แล้ว ขณะนี้ยังไม่รองรับการแชร์ผ่านอินเทอร์เน็ตสาธารณะ',
    scopeNoZones: 'ยังไม่มีการกำหนดช่วงเครือข่ายไว้ จึงสร้างลิงก์แบบจำกัดขอบเขตไม่ได้ ผู้ดูแลระบบเพิ่มได้ที่ ตั้งค่า → การจัดการระบบ → โซนเครือข่าย',
    chipZoneRestricted: 'เครือข่ายที่อนุญาต',
    linkPassword: 'รหัสของลิงก์',
    linkPasswordPlaceholder: 'อย่างน้อย 8 ตัวอักษร',
    linkPasswordHint: 'ผู้รับต้องกรอกรหัสนี้ก่อนจึงจะได้ไฟล์ ส่งรหัสให้เขาแยกจากตัวลิงก์ — ส่งไปพร้อมกันก็ไม่มีประโยชน์',
    linkPasswordTooShort: 'ต้องยาวอย่างน้อย 8 ตัวอักษร',
    shareLinkReady: 'สร้างลิงก์แล้ว',
    copyLink: 'คัดลอกลิงก์',
    shareLinkOnceWarn: 'คัดลอกตอนนี้เลย ระบบเก็บไว้แค่ค่าแฮชของลิงก์ จึงแสดงซ้ำไม่ได้ — ถ้าทำหาย ให้เพิกถอนลิงก์นี้แล้วสร้างใหม่',
    shareLinkPasswordNote: 'ผู้รับจะถูกถามรหัสที่คุณเพิ่งตั้งไว้',
    shareLinkScopeNote: 'เข้าถึงได้จาก:',
    createShare: 'สร้างลิงก์',
    activeLinks: 'ลิงก์แชร์ที่ใช้งานอยู่',
    colScope: 'ขอบเขต',
    colAuth: 'การยืนยัน',
    colExpiresIn: 'หมดอายุใน',
    colCreatedBy: 'สร้างโดย',
    colHits: 'ครั้งที่เปิด',
    revoke: 'เพิกถอน',
    revokeTitle: 'เพิกถอนลิงก์แชร์?',
    revokeBody: 'ลิงก์ของ “{name}” จะตายทันที ใครถือลิงก์อยู่จะไม่ได้อะไรเลย การกระทำนี้ย้อนกลับไม่ได้',
    confirmRevoke: 'เพิกถอนถาวร',
    cancel: 'ยกเลิก',
    expired: 'หมดอายุ',
    chipVlanOnly: 'VLAN เท่านั้น',
    chipSubnet: 'ซับเน็ต',
    chipAnyNetwork: 'เข้าถึง AEGIS ได้',

    current: 'ปัจจุบัน',
    colTimestamp: 'เวลา',

    storageTitle: 'พื้นที่เก็บ & สำรอง',
    capacity: 'ความจุ',
    degraded: 'เสื่อมสภาพ',
    colStatus: 'สถานะ',
    docs: 'เอกสาร',
    media: 'สื่อ',
    archives: 'ไฟล์บีบอัด',
    vaultSeg: 'ห้องนิรภัย',
    free: 'ว่าง',
    storageZeroGb: '0 GB',
    backupTarget: 'ปลายทางสำรอง',
    backupSchedule: 'ตารางเวลา',
    backupScheduleEmpty: 'ยังไม่ได้ตั้งค่าตารางสำรองข้อมูลอัตโนมัติ',
    setupNow: 'ตั้งค่าตอนนี้',

    auditTitle: 'บันทึกตรวจสอบ',
    auditSubtitle: 'บันทึกต่อท้ายอย่างเดียว แก้ไขอะไรไม่ได้',
    colActor: 'ผู้กระทำ',
    colAction: 'การกระทำ',
    colTargetA: 'เป้าหมาย',
    colResult: 'ผลลัพธ์',
    colSourceIp: 'IP ต้นทาง',
    exportCsv: 'ส่งออก CSV',
    filterAll: 'ทั้งหมด',
    filterDenied: 'เฉพาะถูกปฏิเสธ',
    filterActor: 'ผู้กระทำ',
    filterAction: 'การกระทำ',
    filterRange: 'ช่วงเวลา',
    filterScope: 'ขอบเขต',
    filterStatus: 'สถานะ',
    filterActive: 'ยังใช้งานได้',
    filterExpiresWithin: 'หมดอายุภายใน',
    emptyNoAuditFiltered: 'ไม่มีเหตุการณ์ที่ตรงกับตัวกรอง',
    emptyNoSharesFiltered: 'ไม่มีลิงก์ที่ตรงกับตัวกรอง',
    resOk: 'สำเร็จ',
    resDenied: 'ปฏิเสธ',
    resBlocked: 'บล็อก',

    accessTitle: 'ควบคุมสิทธิ์',
    addUser: 'เพิ่มผู้ใช้งาน',
    accessFilter: 'กรองด้วยชื่อหรือชื่อผู้ใช้…',
    accessFilterNone: 'ไม่พบผู้ใช้ที่ตรงกับ “{q}”',
    colUser: 'ผู้ใช้',
    colRole: 'บทบาท',
    colLastLogin: 'เข้าระบบล่าสุด',
    active: 'ใช้งานอยู่',
    accountReady: 'บัญชีพร้อมใช้งาน',
    suspended: 'ระงับ',
    pendingReset: 'รอตั้งรหัสใหม่',
    accessAssignedName: 'ชื่อที่ผู้ดูแลตั้ง',
    pendingResetHint: 'ยังใช้รหัสผ่านชั่วคราว — ถูกปิดกั้นทุกหน้าจนกว่าจะเปลี่ยนรหัส',
    neverLoggedIn: 'ยังไม่เคย',
    tempPasswordIntro: 'สร้างบัญชีแล้ว คัดลอกรหัสผ่านชั่วคราวนี้แล้วส่งต่อให้ผู้ใช้นอกช่องทางนี้ (เช่น พบหน้ากันหรือแชทที่ปลอดภัย) — ระบบจะไม่แสดงซ้ำอีก',
    tempPasswordLabel: 'รหัสผ่านชั่วคราว',
    copyTempPassword: 'คัดลอกรหัสผ่านชั่วคราว',
    copied: 'คัดลอกแล้ว',
    tempPasswordWarn: 'ผู้ใช้ต้องเปลี่ยนรหัสผ่านนี้ในการล็อกอินครั้งแรกก่อนใช้งานส่วนอื่นได้',
    done: 'เสร็จสิ้น',
    permMatrix: 'ตารางสิทธิ์ตามบทบาท',
    permUploadDl: 'อัปโหลด / ดาวน์โหลดไฟล์',
    permShare: 'สร้างลิงก์แชร์',
    permVault: 'ห้องนิรภัยส่วนตัว',
    permSnapRestore: 'กู้คืนเวอร์ชันก่อนหน้าของไฟล์',
    permAudit: 'อ่านบันทึกตรวจสอบ',
    permManageUsers: 'จัดการผู้ใช้และบทบาท',
    firewallNote: 'การแก้ไขโซนไฟร์วอลล์ต้องใช้สิทธิ์ระดับ OS บนโหนด edge — จัดการที่นั่น ไม่ใช่ที่นี่',
    roleAdmin: 'Admin',
    roleUser: 'DataLake-User',
    currentDeviceSession: '1 · เครื่องนี้',
    sessionsThisInstance: 'เซสชัน (อินสแตนซ์นี้)',
    sessionCount: '{n}',
    sessionCountCurrent: '{n} · รวมเครื่องนี้',
    noOtherUsers: 'ยังไม่มีผู้ใช้งานอื่นในระบบ',

    settingsTitle: 'ตั้งค่า',
    setAppearance: 'หน้าตา',
    setAccount: 'บัญชี',
    setSecurity: 'ความปลอดภัย & ความเป็นส่วนตัว',
    setStorageData: 'พื้นที่เก็บ & ข้อมูล',
    setAdmin: 'ผู้ดูแลระบบ',
    theme: 'ธีม',
    themeLight: 'สว่าง',
    themeDark: 'มืด',
    themeSystem: 'ตามระบบ',
    language: 'ภาษา',
    density: 'ความหนาแน่นการแสดงผล',
    densityComfortable: 'สบายตา',
    densityCompact: 'กะทัดรัด',
    profile: 'โปรไฟล์',
    changePassword: 'เปลี่ยนรหัสผ่าน',
    currentPassword: 'รหัสผ่านปัจจุบัน',
    newPassword: 'รหัสผ่านใหม่',
    updatePassword: 'อัปเดตรหัสผ่าน',
    mandatoryResetTitle: 'ตั้งรหัสผ่านใหม่ก่อนเข้าใช้งาน',
    mandatoryResetSubtitle: 'บัญชีนี้ยังใช้รหัสผ่านชั่วคราว ต้องเปลี่ยนก่อนจึงจะเข้าถึงข้อมูลใน Drive ได้',
    temporaryPassword: 'รหัสผ่านชั่วคราวปัจจุบัน',
    confirmNewPassword: 'ยืนยันรหัสผ่านใหม่',
    mandatoryResetSecurityNote: 'รหัสผ่านจะอยู่ในหน่วยความจำชั่วคราวเท่านั้น และไม่ถูกบันทึกลงพื้นที่จัดเก็บของเบราว์เซอร์',
    pwConfirmMismatch: 'รหัสผ่านใหม่ทั้งสองช่องไม่ตรงกัน',
    activeSessions: 'เซสชันที่ใช้งาน',
    thisDevice: 'เครื่องนี้',
    lastActive: 'ใช้งานล่าสุด',
    emptyNoSessions: 'ยังไม่มีเซสชันที่ใช้งานอยู่',
    emptyNoSessionsHint: 'เซสชันจากอุปกรณ์ที่ล็อกอินจะแสดงที่นี่',
    vaultKeyMgmt: 'กุญแจห้องนิรภัย',
    vaultKeyMgmtNote: 'กุญแจอยู่บนอุปกรณ์ของคุณเท่านั้น AEGIS รีเซ็ตให้ไม่ได้ ถ้าหาย ข้อมูลในห้องนิรภัยหายตามไปด้วย',
    shareDefaults: 'ค่าเริ่มต้นลิงก์แชร์',
    encAtRest: 'การเข้ารหัสข้อมูลที่จัดเก็บ',
    encAtRestVault: 'ไฟล์ใน Private Vault ถูกเข้ารหัสในเบราว์เซอร์ของคุณก่อนอัปโหลด — เซิร์ฟเวอร์ถือไว้แค่ ciphertext ที่อ่านไม่ออก และไม่มีกุญแจฝั่งเซิร์ฟเวอร์เข้ามาเกี่ยวข้องเลย',
    encAtRestTodo: 'ไฟล์ทั่วไปใน Data Lake ถูกเก็บบนดิสก์แบบไม่เข้ารหัส ระบบนี้ไม่มีกุญแจ master ฝั่งเซิร์ฟเวอร์ จึงไม่มีอะไรให้หมุนเวียน การทำให้เป็นจริงต้องเข้ารหัสที่ชั้นเก็บไฟล์ พร้อมตัดสินใจว่าจะเก็บตัวกุญแจไว้ที่ไหน',
    notImplemented: 'ยังไม่ได้ทำ',
    designIntent: 'การออกแบบที่ตั้งใจไว้',
    remoteAccessDocNote: 'เอกสารการออกแบบ Twingate เท่านั้น — ยังไม่ได้เชื่อมต่อข้อมูลสถานะคอนเนคเตอร์',
    zonesNote: 'เป็นบันทึกเจตนา ไม่ใช่กลไกบังคับ การบังคับจริงเกิดที่ firewall ของโฮสต์ (UFW/VLAN) การเพิ่ม zone ที่นี่ไม่เปลี่ยนอะไรในแอป',
    shareDefaultsTodo: 'ยังไม่มีการเก็บค่าเริ่มต้นของลิงก์แชร์รายบุคคล ฟอร์มสร้างลิงก์จึงเริ่มจากค่าเดิมทุกครั้ง',
    snapScheduleTodo: 'การตั้งตารางเวลาต้องมีกลไก snapshot ซึ่ง deployment นี้ทำไม่ได้ — ดูจอประวัติไฟล์สำหรับสิ่งที่ทำได้จริง',
    backupTargetsTodo: 'ยังไม่มีการตั้งค่างานสำรองข้อมูลหรือปลายทางใดใน deployment นี้',
    vaultRecoveryTitle: 'วลีกู้คืนห้องนิรภัย (Mnemonic)',
    vaultRecoveryNotConnected: 'ยังไม่ได้สร้าง และระบบกู้คืนยังไม่เชื่อมกับห้องนิรภัยแบบ Zero-Knowledge จึงไม่สร้างชุดคำที่ใช้งานกู้คืนไม่ได้',
    vaultRecoveryUnavailable: 'ชุดคำกู้คืนจริงต้องใช้ BIP-39 และเชื่อมเข้ากับการสร้างกุญแจของห้องนิรภัยก่อน',
    generateRecoveryPhrase: 'สร้างวลีสำหรับกู้คืน 12 คำ',
    remoteAccessTitle: 'การเข้าถึงระยะไกลและอุปกรณ์',
    remoteInactive: 'ไม่ได้ใช้งาน',
    remoteLeastPrivilege: 'สิทธิ์ขั้นต่ำ · มือถือ / นอกสถานที่',
    remoteConnectorStatus: 'สถานะคอนเนคเตอร์',
    remoteReachableResource: 'รีซอร์สที่เข้าถึงได้',
    remoteInactiveHint: 'ยังไม่ได้เชื่อมต่อข้อมูลสถานะคอนเนคเตอร์ สถานะกลางนี้จึงไม่อ้างว่าช่องทางออนไลน์อยู่',
    profileName: 'ชื่อที่แสดง',
    profileNameHint: 'ใช้แสดงทั่วแอปแทนชื่อที่ผู้ดูแลระบบตั้งให้ ชื่อผู้ใช้ของคุณไม่เปลี่ยนและถูกแสดงกำกับไว้เสมอ เว้นว่างเพื่อกลับไปใช้ชื่อที่ผู้ดูแลระบบตั้ง',
    profileAccountName: 'ชื่อที่ผู้ดูแลระบบตั้ง',
    saveProfile: 'บันทึก',
    saving: 'กำลังบันทึก…',
    saved: 'บันทึกแล้ว',
    avatarUpload: 'อัปโหลดรูป',
    avatarRemove: 'ลบรูป',
    avatarHint: 'PNG หรือ JPEG ไม่เกิน 2 MB ข้อมูลตำแหน่งและข้อมูลกล้องจะถูกลบออกก่อนจัดเก็บ',
    avatarTooLarge: 'รูปนี้ใหญ่กว่า 2 MB',
    avatarUnsupported: 'รับเฉพาะรูปแบบ PNG และ JPEG',
    revokeSession: 'ออกจากระบบ',
    sessionsVolatileNote: 'เซสชันเก็บในหน่วยความจำของเซิร์ฟเวอร์ — การรีสตาร์ทเซิร์ฟเวอร์จะทำให้ทุกอุปกรณ์ออกจากระบบ',
    deviceUnknown: 'อุปกรณ์ไม่ทราบชนิด',
    pwPolicyHint: 'ยาวอย่างน้อย 12 ตัวอักษร และต้องไม่ซ้ำกับรหัสเดิมหรือชื่อผู้ใช้ของคุณ',
    pwUpdated: 'เปลี่ยนรหัสผ่านแล้ว',
    pwWeak: 'รหัสผ่านนี้ไม่ผ่านนโยบาย',
    pwWrongCurrent: 'รหัสผ่านปัจจุบันไม่ถูกต้อง',
    networkZones: 'โซนเครือข่าย',
    emptyNoZones: 'ยังไม่มีการกำหนดโซนเครือข่าย',
    zoneName: 'ชื่อโซน',
    zoneCidr: 'CIDR',
    addZone: 'เพิ่มโซน',
    removeZone: 'ลบ',
    zoneNamePlaceholder: 'เช่น VLAN R&D',
    zoneCidrPlaceholder: 'เช่น 10.20.0.0/24',
    invalidZone: 'กรอกชื่อและ CIDR ที่ถูกต้อง (เช่น 10.20.0.0/24)',
    backupTargets: 'ปลายทางสำรองข้อมูล',
    hour1: '1 ชั่วโมง',
    hours24: '24 ชั่วโมง',
    days7: '7 วัน',
    days30: '30 วัน',

    justNow: 'เมื่อครู่',
    minAgo: '{n} นาทีที่แล้ว',
    hourAgo: '{n} ชม.ที่แล้ว',
    dayAgo: '{n} วันที่แล้ว',
    empty: 'ยังไม่มีอะไรที่นี่',
  },

  zh: {
    productName: 'AEGIS Drive_LC',
    productTag: 'AUTONOMOUS EDGE-GUARD INFRASTRUCTURE SYSTEM',
    productLockupSub: '企业级存储 · 安全控制中心',
    breadcrumb: '面包屑导航',
    moreActions: '更多操作',
    errorBoundaryTitle: '发生意外错误',
    errorBoundaryBody: '无法显示此页面。技术详情已记录在浏览器控制台中。',
    errorBoundaryReload: '重新加载',

    loginTitle: '登录',
    loginSubtitle: '安全 NAS · 本地部署',
    username: '用户名',
    password: '密码',
    usernamePlaceholder: '名.姓',
    passwordPlaceholder: '••••••••',
    showPassword: '显示密码',
    hidePassword: '隐藏密码',
    rememberSession: '记住此会话',
    signIn: '登录',
    signingIn: '正在验证…',
    loginFailed: '用户名或密码不正确。',
    lockout: '尝试次数过多——锁定 {s} 秒',
    loginBlockedCsrf: '请求被拦截——来源不匹配。请重新加载页面后再试。',
    loginNetwork: '无法连接服务器。请检查网络后重试。',
    loginTimeout: '服务器响应超时。请重试。',
    loginServerError: '服务器错误——尚未校验凭据。请重试。',

    // 四种界面状态
    errLoadTitle: '无法加载此页面',
    errLoadHint: 'Drive 后端未响应。请确认服务器正在运行，然后重试。',
    errLoadTimeout: '请求超时——Edge 节点可能负载较高，请重试。',
    retry: '重试',
    emptyNoFiles: '暂无文件',
    emptyFolder: '此位置还没有文件或文件夹',
    createFirstFolder: '创建第一个文件夹',
    emptyNoFilesHint: '上传文件或创建文件夹以开始使用。',
    dependencyUnavailableHint: '元数据服务尚未连接，数据目前不可用；这并不表示数据已被删除。',
    dashboardUnavailable: '仪表板数据不可用',
    filesUnavailable: '无法加载文件',
    sharesUnavailable: '安全共享不可用',
    historyUnavailable: '文件历史不可用',
    auditUnavailable: '审计日志不可用',
    accessUnavailable: '访问控制不可用',
    emptyNoShares: '暂无有效共享链接',
    emptyNoSharesHint: '在左侧创建链接——每个链接均带有有效期和网络范围。',
    emptyNoAudit: '暂无审计事件',
    emptyNoAuditHint: '与安全相关的操作将记录在此处。',
    emptyNoUsers: '暂无用户账户',
    emptyNoActivity: '暂无最近活动',
    emptyNoLoginHistory: '暂无登录历史',
    emptyNoRecentFiles: '暂无最近文件',
    notConnected: '尚未连接',
    driveOnline: 'Drive：在线',
    driveNotConnected: 'Drive：尚未连接',
    metadataNotConnected: 'Metadata: 尚未连接',
    metadataConnected: 'Metadata：{source}',
    emptyNoUploads: '暂无上传',
    emptyNoUploadsHint: '将文件拖放到上方，以上传到当前文件夹。',
    dashLoginHistory: '登录历史',
    dashLoginHistorySub: '您最近的登录记录——个人安全状态',
    statSecurity: 'DENIED/BLOCKED 事件（最近 100 条）',
    stFailed: '失败',
    uploadTooLarge: '超过 1 GB 上传上限——此文件未被发送。',
    confirmDeleteTitle: '从数据湖中删除？',
    confirmDeleteBody: '“{name}”及其全部版本历史将被永久删除。没有回收站，也没有任何方式可以恢复。',
    actionFailed: '操作失败——服务器未接受请求，请重试。',
    layerNetwork: 'LAYER 0 · NETWORK',
    layerNetworkDesc: 'VPN + VLAN',
    layerApp: 'LAYER 1 · APPLICATION',
    layerAppDesc: '凭据',
    layerStorage: 'LAYER 2 · STORAGE',
    layerStorageDesc: 'Data Lake · 尚未启用静态加密',
    layerMeta: 'LAYER 3 · METADATA',
    layerMetaDesc: 'PostgreSQL',

    navDashboard: '仪表盘',
    navFiles: '文件',
    navVault: '私人保险库',
    navUploads: '上传',
    navShares: '安全共享链接',
    navVersions: '文件历史',
    versionsTitle: '文件历史',
    versionsMyFiles: '您的文件',
    versionsNone: '暂无历史版本',
    versionsCount: '有 {n} 个历史版本',
    versionsEmptyHint: '再次上传同名文件时，被替换的版本会保存在这里。',
    versionsPickFile: '选择一个文件以查看其历史',
    versionCurrent: '当前',
    versionSupersededBy: '被替换者',
    versionRestore: '恢复',
    versionRestoring: '正在恢复…',
    versionRestored: '已恢复。原本的当前文件现在成为最新的历史版本。',
    versionRestoreTitle: '恢复此版本？',
    versionRestoreBody: '来自 {when} 的版本将成为当前文件。',
    versionRestoreSafe: '不会丢失任何内容——当前文件会被保留为历史版本，因此此操作可以撤销。',
    versionsScopeTitle: '这是按文件的历史记录，而非整个数据湖的快照。',
    versionsScopeBody: '时间点快照需要文件系统提供支持（LVM、ZFS 或 Btrfs），而本部署将文件存放在普通卷上。已删除的文件不保留历史，且这些版本与文件位于同一磁盘上——磁盘故障时同样会丢失。那是异地备份的职责，而目前尚未配置。',
    versionsTrackEmpty: '尚未保存文件版本——替换文件后会显示先前版本。',
    versionsNoFiles: '尚无可显示版本历史的文件',
    notAvailable: '此处无法获取',
    notConfigured: '未配置',
    capacitySub: '读取自存放数据湖的文件系统。',
    capacityTotal: '总容量',
    capacityUsed: '已用',
    capacityUsedPct: '已用',
    capacityUnreadable: '文件系统未报告容量，因此不显示数字，而不是显示一个猜测值。',
    unaccounted: '此卷上的其他内容',
    unaccountedHint: '文件系统计为已用、但并非本应用写入的空间——系统文件、共用该卷的其他容器，或孤立数据。',
    versions: '历史版本',
    other: '其他文件',
    diskHealth: '磁盘健康状态',
    diskHealthWhy: '型号、序列号、温度和 SMART 状态需要原始设备访问权限（smartctl 需要 CAP_SYS_RAWIO）。本容器以非 root 用户无特权运行且未获授权，因此不显示任何数值。要报告这些数据需要在主机层面进行更改，而非增加代码。',
    raidStatus: 'RAID',
    raidWhy: '本部署未配置任何阵列，读取阵列状态还需要主机的 /proc/mdstat。',
    backupJobs: '备份任务',
    backupJobsWhy: '本部署中任何位置都未配置备份作业或目标。在配置之前，数据不会被复制到本机之外。',
    navStorage: '存储与备份',
    navAudit: '审计日志',
    navAccess: '访问控制',
    navSettings: '设置',
    navGroupWorkspace: '工作区',
    navGroupProtection: '防护',
    navGroupAdmin: '管理',
    storageMeter: '存储',
    of: '/',
    collapseSidebar: '收起侧栏',
    expandSidebar: '展开侧栏',
    signOut: '退出登录',

    searchPlaceholder: '搜索文件、人员、操作…',
    searchDashboardPlaceholder: '搜索 AEGIS Drive…',
    searchFilesPlaceholder: '搜索文件和文件夹…',
    searchUploadsPlaceholder: '搜索上传和操作…',
    searchSharesPlaceholder: '搜索共享链接和文件…',
    searchVersionsPlaceholder: '搜索文件或版本…',
    searchStoragePlaceholder: '搜索存储与备份…',
    searchAuditPlaceholder: '搜索事件、用户、IP 或资源…',
    searchPeoplePlaceholder: '搜索用户…',
    searchSettingsPlaceholder: '搜索设置和操作…',
    searchSecRecent: '最近',
    searchSecSuggested: '建议',
    searchSecFiles: '文件',
    searchSecPeople: '人员',
    searchSecActions: '操作',
    searchNoRecent: '暂无最近文件',
    searchNoResults: '没有与“{q}”匹配的结果',
    searchNoResultsHint: '请检查拼写，或尝试文件名、人员或页面名称。',
    searchJumpTo: '跳转到该页面',
    searchUnavailable: '无法搜索 — 私人保险库已加密',
    searchUnavailableVault: '保险库内无法搜索 — 其内容采用零知识加密',
    edgeNodeOnline: 'EDGE NODE · 在线',
    notifications: '通知',
    previewAs: '预览',
    previewAsTooltip: '开发者预览 — 切换模拟服务器签发的角色，不属于认证流程。',

    dashTitle: '仪表盘',
    quickActions: '快捷操作',
    quickUploadLabel: '上传',
    quickShareLabel: '共享',
    quickVaultLabel: '保险库',
    uploadFile: '上传文件',
    uploadFileHint: '直接上传到当前文件夹',
    createShareLink: '创建共享链接',
    createShareLinkHint: '设置有效期和访问策略',
    openPrivateVault: '打开私人保险库',
    openPrivateVaultHint: '打开加密工作区',
    preferencesSaving: '正在保存偏好设置…',
    preferencesSaveFailed: '无法保存偏好设置；当前选择仅在本次会话中有效。',
    statStorage: '已用存储空间',
    statFiles: '文件总数',
    statSessions: '活动会话',
    statAlerts: '完整性警报 (24h)',
    vsLastWeek: '对比上周',
    allClear: '一切正常',
    lakeHealth: 'Data Lake 运行状态',
    lakeSubtitle: '三层 · 仅显示实测状态',
    serverTelemetry: '服务器运行指标',
    serverTelemetrySub: '主机指标 · 已为未来真实数据源准备界面',
    telemetryCpu: 'CPU',
    telemetryRam: 'RAM',
    telemetryDisk: '磁盘',
    telemetryNetwork: '网络',
    telemetryTwingate: 'Twingate',
    telemetryUptime: '系统运行时间',
    telemetryUsage: '使用率',
    telemetryValueUnavailable: '无数据',
    telemetryNoSource: '尚未连接遥测数据源',
    telemetryStateLoading: '加载中',
    telemetryStateNormal: '正常',
    telemetryStateWarning: '警告',
    telemetryStateCritical: '严重',
    telemetryStateUnavailable: '不可用',
    tierApp: 'APPLICATION LAYER',
    tierMeta: 'METADATA LAYER',
    tierStorage: 'STORAGE LAYER',
    tierHealthy: '健康',
    tierDegraded: '降级',
    tierDown: '宕机',
    latencyUnavailable: '暂无数据',
    latency: '延迟',
    activity: '动态',
    storageBreakdown: '存储构成',
    activityTitle: '活动',
    activitySub: '每日成功的上传与下载次数，取自审计日志。',
    activityEmpty: '过去 7 天没有活动',
    activityEmptyHint: '上传和下载发生时会显示在这里。',
    recentFiles: '最近的文件',
    ofTotal: '/',
    storageBreakdownSub: '本应用所存储的内容，按类型划分。',
    storageBreakdownFree: '此卷上的可用空间：',
    uploads: '上传',
    downloads: '下载',
    projected: '预测',

    filesTitle: '文件',
    upload: '上传',
    newFolder: '新建文件夹',
    gridView: '网格视图',
    listView: '列表视图',
    sortBy: '排序',
    sortName: '名称',
    sortSize: '大小',
    sortModified: '修改时间',
    colName: '名称',
    colSize: '大小',
    colType: '类型',
    colModified: '修改时间',
    colEncryption: '存储保护',
    encServer: 'Data Lake · 尚未启用静态加密',
    encVault: '保险库密文',
    selected: '已选',
    download: '下载',
    move: '移动',
    delete: '删除',
    rename: '重命名',
    createLink: '创建安全链接',
    createSecureShare: '创建安全共享',
    viewHistory: '查看历史记录',
    filter: '筛选',
    allFileTypes: '所有文件类型',
    filesDropHint: '将文件拖放到此工作区以上传到当前文件夹',
    emptyNoFilesFiltered: '没有符合此搜索或筛选条件的文件',
    verifySha: '校验 SHA-256',
    viewMetadata: '查看元数据',
    fileDetails: '文件详情',
    size: '大小',
    type: '类型',
    uploader: '上传者',
    uploadedAt: '上传时间',
    storagePath: '存储路径',
    integrity: '完整性',
    integrityOk: '已校验',
    integrityPending: '尚未校验',
    integrityFail: '不匹配',
    verifyChecksum: '校验校验和',
    verifying: '校验中…',
    integrityVerified: '✓ 完整性已验证',
    integrityMismatch: '✕ 校验和不匹配',
    verifyUnavailable: '无法验证，因为服务器无法读取已存储的字节。',
    verifyUnavailableVault: '服务器无法验证保险库明文；解密与 AES-GCM 认证仅在浏览器中进行。',
    copyHash: '复制哈希',
    close: '关闭',

    vaultTitle: '私人保险库',
    vaultWarning: '零知识加密 · 密钥丢失不可恢复',
    vaultCipherCaption: 'CIPHERTEXT · 服务器无法读取',
    vaultLocked: '已锁定',
    vaultUnlocked: '已解锁',
    unlockVault: '解锁保险库',
    lockVault: '锁定保险库',
    decrypt: '解密',
    vaultKeyLabel: '保险库密钥',
    vaultKeyNote: '密钥仅在此浏览器内解密文件，永不发送到服务器 — 服务器只保存它无法读取的密文。',
    vaultNoSearch: '没有缩略图，没有内容搜索 — 这正是重点。',
    vaultWrongKey: '解密失败 — 该密钥无法打开此保险库。',
    vaultUnlockUnavailable: '无法在此浏览器中运行解密引擎——尚未校验你的密钥。请重新加载页面；若仍然如此，说明该页面被禁止运行 WebAssembly。',
    vaultSetupTitle: '创建保险库密钥',
    vaultSetupIntro: '此密钥与账户密码相互独立。它在此浏览器中生成，永不发送给 AEGIS。',
    vaultSetupCreate: '创建保险库',
    vaultSetupNeeded: '尚未创建保险库',
    vaultSetupCta: '设置保险库',
    vaultKeyConfirmLabel: '再次输入密钥',
    vaultKeyMismatch: '两次输入不一致。',
    vaultKeyTooShort: '至少使用 12 个字符。这把密钥是攻击者与你的文件之间唯一的屏障。',
    vaultSetupAck: '我明白：一旦丢失此密钥，这些文件将永久丢失，AEGIS 无法重置。',
    vaultDeriving: '正在派生密钥…',
    vaultDecrypting: '正在解密…',
    vaultDownload: '下载',
    vaultAutoLocked: '闲置 10 分钟后保险库已自动重新锁定。',
    vaultUnnamed: '无法读取的条目',
    vaultSecurityBanner: 'AES-256-GCM · 零知识 · 加密和解密均在此浏览器中完成',
    emptyVault: '私人保险库中还没有文件',
    encryptFirstFile: '加密第一个文件',

    uploadsTitle: '上传',
    uploadFiles: '上传文件',
    uploadQueue: '上传队列',
    uploadNeedsAttention: '上传需要处理',
    uploadSuccessTitle: '上传完成',
    uploadSuccessBody: '{name} 已成功上传。',
    destinationFolder: '目标文件夹',
    currentFolder: '当前文件夹',
    uploadWaiting: '等待中',
    uploadProcessing: '处理中',
    uploadComplete: '已完成',
    uploadFailed: '失败',
    uploadCancelled: '已取消',
    cancelAll: '全部取消',
    dismiss: '移除',
    closeUpload: '关闭上传面板',
    chooseFiles: '选择文件',
    dropHere: '拖放文件到此处，或点击选择',
    dropSub: '存储到 Data Lake · 尚未配置静态加密',
    stStaged: '已就绪',
    stEncrypting: '加密中',
    stTransferring: '传输中',
    stHashing: '哈希中',
    stIndexed: '已索引',
    recentUploads: '最近上传',
    simulateUpload: '模拟传入文件',

    sharesTitle: '安全共享链接',
    newShare: '新建共享链接',
    shareFile: '文件',
    expiry: '有效期',
    authMethod: '验证',
    authPassword: '密码',
    authOtc: '一次性验证码',
    authNone: '无',
    networkScope: '网络范围',
    scopeVlan: '仅公司 VLAN',
    scopeSubnet: '指定子网',
    scopeAny: '任何可访问 AEGIS 的网络',
    newShareSub: '接收者必须位于已能访问 AEGIS 的网络。当前不支持通过公共互联网共享。',
    scopeZones: '已批准的网络',
    scopeZonesTitle: '仅限已批准的网络',
    scopeZonesBody: '仅当 AEGIS 可见的来源地址位于管理员定义的网络范围内时，该链接才有效。Twingate 接收者可能显示为连接器可见地址。',
    scopeEnforcementNote: '应用层 CIDR 强制仅用于纵深防御，不能替代 Twingate 访问策略或设备策略。',
    scopeAnyTitle: '任何可访问 AEGIS 的网络',
    scopeAnyBody: '持有链接的人可以从已能访问 AEGIS 的网络下载。当前不支持通过公共互联网共享。',
    scopeNoZones: '尚未定义任何网络范围，因此无法创建受限链接。管理员可在“设置 → 管理员 → 网络区域”中添加。',
    chipZoneRestricted: '已批准网络',
    linkPassword: '链接密码',
    linkPasswordPlaceholder: '至少 8 个字符',
    linkPasswordHint: '接收者需先输入此密码才能获得文件。请与链接分开发送——两者一起发送就失去了意义。',
    linkPasswordTooShort: '请至少使用 8 个字符。',
    shareLinkReady: '链接已创建',
    copyLink: '复制链接',
    shareLinkOnceWarn: '请立即复制。系统仅保存链接的哈希值，因此无法再次显示——如果丢失，请撤销此链接并重新创建。',
    shareLinkPasswordNote: '接收者将被要求输入您刚刚设置的密码。',
    shareLinkScopeNote: '仅可从以下位置访问：',
    createShare: '创建链接',
    activeLinks: '活跃共享链接',
    colScope: '范围',
    colAuth: '验证',
    colExpiresIn: '剩余时间',
    colCreatedBy: '创建者',
    colHits: '访问次数',
    revoke: '撤销',
    revokeTitle: '撤销共享链接？',
    revokeBody: '“{name}” 的链接将立即失效，持有链接者将一无所获。此操作无法撤销。',
    confirmRevoke: '永久撤销',
    cancel: '取消',
    expired: '已过期',
    chipVlanOnly: '仅 VLAN',
    chipSubnet: '子网',
    chipAnyNetwork: '可访问 AEGIS',

    current: '当前',
    colTimestamp: '时间',

    storageTitle: '存储与备份',
    capacity: '容量',
    degraded: '降级',
    colStatus: '状态',
    docs: '文档',
    media: '媒体',
    archives: '归档',
    vaultSeg: '保险库',
    free: '可用',
    storageZeroGb: '0 GB',
    backupTarget: '备份目标',
    backupSchedule: '计划',
    backupScheduleEmpty: '尚未配置自动备份计划',
    setupNow: '立即设置',

    auditTitle: '审计日志',
    auditSubtitle: '仅追加。此处内容不可编辑。',
    colActor: '操作者',
    colAction: '操作',
    colTargetA: '目标',
    colResult: '结果',
    colSourceIp: '来源 IP',
    exportCsv: '导出 CSV',
    filterAll: '全部',
    filterDenied: '仅被拒绝',
    filterActor: '操作者',
    filterAction: '操作',
    filterRange: '时间范围',
    filterScope: '范围',
    filterStatus: '状态',
    filterActive: '有效',
    filterExpiresWithin: '将在此期限内过期',
    emptyNoAuditFiltered: '没有符合筛选条件的事件',
    emptyNoSharesFiltered: '没有符合筛选条件的链接',
    resOk: '成功',
    resDenied: '拒绝',
    resBlocked: '阻止',

    accessTitle: '访问控制',
    addUser: '添加用户',
    accessFilter: '按姓名或用户名筛选…',
    accessFilterNone: '没有与“{q}”匹配的用户',
    colUser: '用户',
    colRole: '角色',
    colLastLogin: '最近登录',
    active: '活跃',
    accountReady: '账户可用',
    suspended: '停用',
    pendingReset: '待重设密码',
    accessAssignedName: '指定名称',
    pendingResetHint: '仍在使用临时密码——在更改之前将被阻止访问所有页面。',
    neverLoggedIn: '从未',
    tempPasswordIntro: '账户已创建。请复制此临时密码并通过带外方式（如当面告知或安全聊天）转交给用户——此密码不会再次显示。',
    tempPasswordLabel: '临时密码',
    copyTempPassword: '复制临时密码',
    copied: '已复制',
    tempPasswordWarn: '用户必须在首次登录时重设此密码，之后才能使用其他功能。',
    done: '完成',
    permMatrix: '角色权限参考',
    permUploadDl: '上传 / 下载文件',
    permShare: '创建共享链接',
    permVault: '私人保险库',
    permSnapRestore: '恢复文件的历史版本',
    permAudit: '读取审计日志',
    permManageUsers: '管理用户与角色',
    firewallNote: '防火墙区域更改需要边缘节点上的 OS 特权 — 在节点上管理，而非此处。',
    roleAdmin: 'Admin',
    roleUser: 'DataLake-User',
    currentDeviceSession: '1 · 本设备',
    sessionsThisInstance: '会话（此实例）',
    sessionCount: '{n}',
    sessionCountCurrent: '{n} · 包含本设备',
    noOtherUsers: '系统中尚无其他用户',

    settingsTitle: '设置',
    setAppearance: '外观',
    setAccount: '账户',
    setSecurity: '安全与隐私',
    setStorageData: '存储与数据',
    setAdmin: '管理员',
    theme: '主题',
    themeLight: '浅色',
    themeDark: '深色',
    themeSystem: '跟随系统',
    language: '语言',
    density: '显示密度',
    densityComfortable: '舒适',
    densityCompact: '紧凑',
    profile: '个人资料',
    changePassword: '修改密码',
    currentPassword: '当前密码',
    newPassword: '新密码',
    updatePassword: '更新密码',
    mandatoryResetTitle: '请先保护账户，然后继续',
    mandatoryResetSubtitle: '此账户仍在使用临时密码。更改密码后才能访问 Drive 数据。',
    temporaryPassword: '当前临时密码',
    confirmNewPassword: '确认新密码',
    mandatoryResetSecurityNote: '密码仅保存在内存中，不会写入浏览器存储。',
    pwConfirmMismatch: '两次输入的新密码不一致。',
    activeSessions: '活动会话',
    thisDevice: '本设备',
    lastActive: '最近活动',
    emptyNoSessions: '暂无活动会话',
    emptyNoSessionsHint: '已登录设备的会话将显示在此处。',
    vaultKeyMgmt: '保险库密钥',
    vaultKeyMgmtNote: '密钥只存在于你的设备上。AEGIS 无法为你重置。密钥丢失，保险库内容随之丢失。',
    shareDefaults: '共享链接默认值',
    encAtRest: '静态加密',
    encAtRestVault: '私人保险库中的文件在上传前已在您的浏览器中加密——服务器只持有无法读取的密文，整个过程不涉及任何服务器端密钥。',
    encAtRestTodo: '普通数据湖上传的文件以未加密方式存储在磁盘上。本系统没有服务器端主密钥，因此没有可轮换的内容。要实现此功能需要在存储层加密，并决定密钥材料的存放位置。',
    notImplemented: '尚未实现',
    designIntent: '设计意图',
    remoteAccessDocNote: '仅作为 Twingate 设计参考——尚未连接连接器遥测。',
    zonesNote: '这是意图记录，而非控制手段。实际强制在主机防火墙（UFW/VLAN）上进行；在此添加区域不会改变应用中的任何行为。',
    shareDefaultsTodo: '尚未保存每位用户的共享默认值，因此新建链接表单每次都从相同的值开始。',
    snapScheduleTodo: '计划任务需要快照机制，而本部署无法提供——请参阅“文件历史”了解可用的替代方案。',
    backupTargetsTodo: '此部署中未配置任何备份作业或目标。',
    vaultRecoveryTitle: '保险库恢复短语（Mnemonic）',
    vaultRecoveryNotConnected: '尚未生成。恢复功能尚未连接到当前零知识保险库，因此不会伪造无法恢复数据的短语。',
    vaultRecoveryUnavailable: '真正的恢复短语需要 BIP-39，并与保险库密钥派生流程集成。',
    generateRecoveryPhrase: '生成 12 词恢复短语',
    remoteAccessTitle: '远程访问与设备',
    remoteInactive: '未启用',
    remoteLeastPrivilege: '最小权限访问 · 移动设备 / 异地',
    remoteConnectorStatus: '连接器状态',
    remoteReachableResource: '可访问资源',
    remoteInactiveHint: '尚未连接连接器遥测。此中性状态不会声称通道在线。',
    profileName: '显示名称',
    profileNameHint: '在整个应用中代替管理员设置的名称显示。您的用户名永不更改，并始终显示在旁边。留空即恢复使用管理员设置的名称。',
    profileAccountName: '管理员指定的名称',
    saveProfile: '保存',
    saving: '正在保存…',
    saved: '已保存',
    avatarUpload: '上传头像',
    avatarRemove: '移除',
    avatarHint: 'PNG 或 JPEG，最大 2 MB。文件存储前会移除位置和相机元数据。',
    avatarTooLarge: '该图片大于 2 MB。',
    avatarUnsupported: '仅接受 PNG 和 JPEG 图片。',
    revokeSession: '退出登录',
    sessionsVolatileNote: '会话保存在服务器内存中——重启服务器会让所有设备退出登录。',
    deviceUnknown: '未知设备',
    pwPolicyHint: '至少 12 个字符，且不能与当前密码或用户名相同。',
    pwUpdated: '密码已更新',
    pwWeak: '该密码不符合策略要求。',
    pwWrongCurrent: '当前密码不正确。',
    networkZones: '网络区域',
    emptyNoZones: '尚未定义网络区域',
    zoneName: '区域名称',
    zoneCidr: 'CIDR',
    addZone: '添加区域',
    removeZone: '移除',
    zoneNamePlaceholder: '例如 R&D VLAN',
    zoneCidrPlaceholder: '例如 10.20.0.0/24',
    invalidZone: '请输入名称和有效的 CIDR（例如 10.20.0.0/24）',
    backupTargets: '备份目标',
    hour1: '1 小时',
    hours24: '24 小时',
    days7: '7 天',
    days30: '30 天',

    justNow: '刚刚',
    minAgo: '{n} 分钟前',
    hourAgo: '{n} 小时前',
    dayAgo: '{n} 天前',
    empty: '这里还没有内容',
  },
}

/** Simple template fill: t('revokeBody', { name }) */
export function makeT(lang) {
  const table = STRINGS[lang] ?? STRINGS.en
  return (key, vars) => {
    let s = table[key] ?? STRINGS.en[key] ?? key
    if (vars) for (const [k, v] of Object.entries(vars)) s = s.replaceAll(`{${k}}`, String(v))
    return s
  }
}
