// Flat i18n table — every user-facing string flows through here.
// No hardcoded UI copy in JSX. Mock DATA (filenames, people) stays literal.
export const LANGS = ['en', 'th', 'zh']

export const STRINGS = {
  en: {
    productName: 'AEGIS Drive_LC',
    productTag: 'AUTONOMOUS EDGE-GUARD INFRASTRUCTURE SYSTEM',

    // login
    loginTitle: 'Sign in',
    loginSubtitle: 'Secure NAS · on-premise',
    username: 'Username',
    password: 'Password',
    usernamePlaceholder: 'your.name',
    passwordPlaceholder: '••••••••',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    rememberSession: 'Remember this session',
    signIn: 'Sign in',
    signingIn: 'Verifying…',
    loginFailed: 'Invalid username or password.',
    lockout: 'Too many attempts — locked for {s}s',
    // ── ความล้มเหลวที่ "ไม่ได้เกิดจากรหัสผ่าน" — ต้องไม่ถูกแสดงเป็น loginFailed เด็ดขาด
    loginBlockedCsrf: 'Request blocked — origin mismatch. Please reload the page and try again.',
    loginNetwork: 'Cannot reach the server. Check your connection and try again.',
    loginTimeout: 'The server took too long to respond. Please try again.',
    loginServerError: 'Server error — your credentials were not checked. Please try again.',

    // Four UI states (loading = skeleton, no strings needed)
    errLoadTitle: 'Could not load this screen',
    errLoadHint: 'The Drive backend did not respond. Check that the server is running, then try again.',
    errLoadTimeout: 'The request timed out. The Edge node may be under load — try again.',
    retry: 'Retry',
    emptyNoFiles: 'No files yet',
    emptyNoFilesHint: 'Files you upload to the data lake will appear here.',
    emptyNoStorage: 'No storage data available',
    emptyNoStorageHint: 'Capacity, disk, and backup status will appear here once reported by the Edge node.',
    emptyNoShares: 'No active share links',
    emptyNoSharesHint: 'Create a link on the left — every link carries an expiry and a network scope.',
    emptyNoSnapshots: 'No snapshots yet',
    emptyNoSnapshotsHint: 'Automatic snapshots will appear here as the schedule runs.',
    emptyNoAudit: 'No audit events yet',
    emptyNoAuditHint: 'Security-relevant actions will be recorded here as they happen.',
    emptyNoUsers: 'No user accounts',
    emptyNoActivity: 'No recent activity',
    emptyNoUploads: 'No uploads yet',
    emptyNoUploadsHint: 'Drop files above to store them encrypted on the NAS.',
    dashLoginHistory: 'Login history',
    dashLoginHistorySub: 'Your recent sign-ins — personal security status',
    statSecurity: 'Security events',
    stFailed: 'Failed',
    confirmDeleteTitle: 'Delete from the data lake?',
    confirmDeleteBody: '“{name}” will be removed. Snapshots made before this point can still restore it.',
    actionFailed: 'The action failed — the server did not accept the request. Try again.',
    layerNetwork: 'LAYER 0 · NETWORK',
    layerNetworkDesc: 'VPN + VLAN',
    layerApp: 'LAYER 1 · APPLICATION',
    layerAppDesc: 'Credentials',
    layerStorage: 'LAYER 2 · STORAGE',
    layerStorageDesc: 'Encryption at rest',
    layerMeta: 'LAYER 3 · METADATA',
    layerMetaDesc: 'PostgreSQL',

    // nav
    navDashboard: 'Dashboard',
    navFiles: 'Files',
    navVault: 'Private Vault',
    navUploads: 'Uploads',
    navShares: 'Secure Shares',
    navSnapshots: 'Snapshots',
    navStorage: 'Storage & Backup',
    navAudit: 'Audit Log',
    navAccess: 'Access Control',
    navSettings: 'Settings',
    navGroupWorkspace: 'Workspace',
    navGroupProtection: 'Protection',
    navGroupAdmin: 'Administration',
    storageMeter: 'Storage',
    upgradeStorage: 'UPGRADE STORAGE',
    of: 'of',
    collapseSidebar: 'Collapse sidebar',
    expandSidebar: 'Expand sidebar',
    signOut: 'Sign out',

    // top bar
    searchPlaceholder: 'Search files, people, actions…',
    searchSecRecent: 'Recent',
    searchSecSuggested: 'Suggested',
    searchSecFiles: 'Files',
    searchSecPeople: 'People',
    searchSecActions: 'Actions',
    searchNoRecent: 'No recent files',
    searchNoResults: 'No results for “{q}”',
    searchNoResultsHint: 'Check the spelling, or try a file name, a person, or a screen name.',
    searchJumpTo: 'Jump to screen',
    searchUnavailable: 'Search unavailable — Private Vault is encrypted',
    // ทูลทิปของช่องค้นหาที่ถูกปิดในจอ Vault — อธิบาย "ทำไม" ไม่ใช่แค่ "ไม่ได้"
    searchUnavailableVault: 'Search is unavailable in the Private Vault — its contents are zero-knowledge encrypted',
    edgeNodeOnline: 'EDGE NODE · ONLINE',
    notifications: 'Notifications',
    previewAs: 'PREVIEW',
    previewAsTooltip: 'Developer preview — swaps the mock server-issued role. Not part of authentication.',

    // dashboard
    dashTitle: 'Dashboard',
    statStorage: 'Storage used',
    statFiles: 'Files indexed',
    statSessions: 'Active sessions',
    statAlerts: 'Integrity alerts (24h)',
    vsLastWeek: 'vs last week',
    allClear: 'All clear',
    lakeHealth: 'Data Lake Health',
    lakeSubtitle: 'Three tiers, live',
    tierApp: 'APPLICATION LAYER',
    tierMeta: 'METADATA LAYER',
    tierStorage: 'STORAGE LAYER',
    tierHealthy: 'HEALTHY',
    tierDegraded: 'DEGRADED',
    tierDown: 'DOWN',
    latency: 'latency',
    activity: 'Activity',
    storageBreakdown: 'Storage breakdown',
    transferActivity: 'Upload / Download activity',
    uploads: 'Uploads',
    downloads: 'Downloads',
    projected: 'projected',
    demoControls: 'DEMO',

    // files
    filesTitle: 'Files',
    upload: 'Upload',
    newFolder: 'New folder',
    gridView: 'Grid view',
    listView: 'List view',
    sortBy: 'Sort',
    sortName: 'Name',
    sortSize: 'Size',
    sortModified: 'Modified',
    colName: 'NAME',
    colSize: 'SIZE',
    colType: 'TYPE',
    colModified: 'MODIFIED',
    colEncryption: 'ENCRYPTION',
    encServer: 'Server-side · indexed',
    encVault: 'Vault ciphertext',
    selected: 'selected',
    download: 'Download',
    move: 'Move',
    delete: 'Delete',
    rename: 'Rename',
    createLink: 'Create secure link',
    verifySha: 'Verify SHA-256',
    viewMetadata: 'View metadata',
    fileDetails: 'File details',
    size: 'Size',
    type: 'Type',
    uploader: 'Uploader',
    uploadedAt: 'Uploaded at',
    storagePath: 'Storage path',
    integrity: 'Integrity',
    integrityOk: 'VERIFIED',
    integrityPending: 'NOT VERIFIED YET',
    integrityFail: 'MISMATCH',
    verifyChecksum: 'VERIFY CHECKSUM',
    verifying: 'VERIFYING…',
    integrityVerified: '✓ INTEGRITY VERIFIED',
    integrityMismatch: '✕ CHECKSUM MISMATCH',
    copyHash: 'Copy hash',
    copied: 'Copied',
    close: 'Close',

    // vault
    vaultTitle: 'Private Vault',
    vaultWarning: 'ZERO-KNOWLEDGE ENCRYPTION · KEY LOSS IS UNRECOVERABLE',
    vaultCipherCaption: 'CIPHERTEXT · NOT READABLE BY SERVER',
    vaultLocked: 'Vault locked',
    vaultUnlocked: 'Vault unlocked',
    unlockVault: 'Unlock vault',
    lockVault: 'Lock vault',
    decrypt: 'Decrypt',
    vaultKeyLabel: 'Vault key',
    vaultKeyNote: 'Your key decrypts files in this browser only. It is never sent to the server — the server stores ciphertext it cannot read.',
    vaultNoSearch: 'No thumbnails. No content search. That is the point.',
    vaultWrongKey: 'Decryption failed — that key does not open this vault.',
    // คนละเรื่องกับกุญแจผิด: เครื่องมือเข้ารหัสในเบราว์เซอร์ทำงานไม่ได้เลย
    vaultUnlockUnavailable: 'Cannot run the decryption engine in this browser — your key was never checked. Reload the page; if this persists, the page may be blocked from running WebAssembly.',
    vaultSetupTitle: 'Create your vault key',
    vaultSetupIntro: 'This key is separate from your account password. It is created in this browser and never sent to AEGIS.',
    vaultSetupCreate: 'Create vault',
    vaultSetupNeeded: 'No vault yet',
    vaultSetupCta: 'Set up vault',
    vaultKeyConfirmLabel: 'Repeat vault key',
    vaultKeyMismatch: 'The two entries do not match.',
    vaultKeyTooShort: 'Use at least 12 characters. This key is the only thing standing between an attacker and your files.',
    vaultSetupAck: 'I understand that if I lose this key, these files are gone forever. AEGIS cannot reset it.',
    vaultDeriving: 'Deriving key…',
    vaultDecrypting: 'Decrypting…',
    vaultDownload: 'Download',
    vaultAutoLocked: 'Vault re-locked after 10 minutes of inactivity.',
    vaultUnnamed: 'Unreadable entry',

    // uploads
    uploadsTitle: 'Uploads',
    dropHere: 'Drop files here, or click to browse',
    dropSub: 'Files are encrypted before they touch the disk',
    stStaged: 'STAGED',
    stEncrypting: 'ENCRYPTING',
    stTransferring: 'TRANSFERRING',
    stHashing: 'HASHING',
    stIndexed: 'INDEXED',
    recentUploads: 'Recent uploads',
    simulateUpload: 'Simulate incoming files',

    // shares
    sharesTitle: 'Secure Shares',
    newShare: 'New share link',
    shareFile: 'File',
    expiry: 'Expiry',
    authMethod: 'Auth',
    authPassword: 'Password',
    authOtc: 'One-time code',
    authNone: 'None',
    networkScope: 'NETWORK SCOPE',
    scopeVlan: 'Company VLAN only',
    scopeSubnet: 'Specific subnet',
    scopeAny: 'Any network',
    scopeDiagramNote: 'A request from a blocked zone is dropped by the firewall before it reaches the file.',
    zoneCompany: 'Company VLAN',
    zoneGuest: 'Guest VLAN',
    zoneInternet: 'Internet',
    createShare: 'Create link',
    activeLinks: 'Active links',
    colScope: 'SCOPE',
    colAuth: 'AUTH',
    colExpiresIn: 'EXPIRES IN',
    colCreatedBy: 'CREATED BY',
    colHits: 'HITS',
    revoke: 'Revoke',
    revokeTitle: 'Revoke share link?',
    revokeBody: 'The link for “{name}” dies immediately. Anyone holding it gets nothing. This cannot be undone.',
    confirmRevoke: 'Revoke permanently',
    cancel: 'Cancel',
    expired: 'EXPIRED',
    chipVlanOnly: 'VLAN ONLY',
    chipSubnet: 'SUBNET',
    chipAnyNetwork: 'ANY NETWORK',

    // snapshots
    snapshotsTitle: 'Snapshots & Recovery',
    snapshotTimeline: 'Timeline',
    current: 'CURRENT',
    colId: 'ID',
    colTimestamp: 'TIMESTAMP',
    colDelta: 'SIZE DELTA',
    colVerified: 'VERIFIED',
    rollback: 'Rollback',
    rollbackTitle: 'Roll back to snapshot?',
    rollbackWhatRestored: 'Everything the volume held at {time} comes back — files, metadata, permissions.',
    rollbackWhatLost: 'Every change made after that moment is destroyed: {delta} of writes.',
    rollbackTypeToConfirm: 'Type the snapshot ID to confirm',
    rollbackConfirm: 'Roll back now',
    restoring: 'RESTORING SNAPSHOT…',
    restored: 'Snapshot restored. The volume is back to {id}.',

    // storage
    storageTitle: 'Storage & Backup',
    capacity: 'Capacity',
    raidTitle: 'RAID 1 Mirror',
    synced: 'SYNCED',
    degraded: 'DEGRADED',
    rebuilding: 'REBUILDING',
    unprotected: '⚠ UNPROTECTED',
    diskFailed: 'DISK LOST',
    temperature: 'Temp',
    smart: 'SMART',
    powerOn: 'Power-on',
    hours: 'h',
    backupSchedule: 'Backup schedule',
    colJob: 'JOB',
    colTarget: 'TARGET',
    colFrequency: 'FREQUENCY',
    colLastRun: 'LAST RUN',
    colStatus: 'STATUS',
    colNextRun: 'NEXT RUN IN',
    docs: 'Documents',
    media: 'Media',
    archives: 'Archives',
    vaultSeg: 'Vault',
    free: 'Free',

    // audit
    auditTitle: 'Audit Log',
    auditSubtitle: 'Append-only. Nothing here can be edited.',
    colActor: 'ACTOR',
    colAction: 'ACTION',
    colTargetA: 'TARGET',
    colResult: 'RESULT',
    colSourceIp: 'SOURCE IP',
    exportCsv: 'Export CSV',
    filterAll: 'All',
    filterDenied: 'Denied only',
    filterActor: 'Actor',
    filterAction: 'Action',
    filterRange: 'Date range',
    filterScope: 'Scope',
    filterStatus: 'Status',
    filterActive: 'Active',
    filterExpiresWithin: 'Expires within',
    emptyNoAuditFiltered: 'No events match these filters',
    emptyNoSharesFiltered: 'No links match these filters',
    resOk: 'OK',
    resDenied: 'DENIED',
    resBlocked: 'BLOCKED',

    // access
    accessTitle: 'Access Control',
    addUser: 'Add user',
    accessFilter: 'Filter by name or username…',
    accessFilterNone: 'No users match “{q}”',
    colUser: 'USER',
    colRole: 'ROLE',
    colLastLogin: 'LAST LOGIN',
    active: 'ACTIVE',
    suspended: 'SUSPENDED',
    pendingReset: 'PENDING RESET',
    pendingResetHint: 'Still on a temporary password — blocked from every screen until it is changed.',
    neverLoggedIn: 'Never',
    tempPasswordIntro: 'Account created. Copy this temporary password and hand it to the user out-of-band (e.g. in person or a secure chat) — it will not be shown again.',
    tempPasswordLabel: 'Temporary password',
    copyTempPassword: 'Copy temporary password',
    copied: 'Copied',
    tempPasswordWarn: 'The user must reset this password on their first login before they can use anything else.',
    done: 'Done',
    permMatrix: 'Permission matrix',
    permUploadDl: 'Upload / download files',
    permShare: 'Create share links',
    permVault: 'Private Vault',
    permSnapRestore: 'Restore snapshots',
    permAudit: 'Read audit log',
    permManageUsers: 'Manage users & roles',
    firewallNote: 'Firewall-zone changes require elevated OS privileges on the edge node — they are managed there, not here.',
    roleAdmin: 'Admin',
    roleUser: 'DataLake-User',

    // settings
    settingsTitle: 'Settings',
    setAppearance: 'Appearance',
    setAccount: 'Account',
    setSecurity: 'Security & Privacy',
    setStorageData: 'Storage & Data',
    setAdmin: 'Administration',
    theme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    language: 'Language',
    density: 'Display density',
    densityComfortable: 'Comfortable',
    densityCompact: 'Compact',
    profile: 'Profile',
    changePassword: 'Change password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    updatePassword: 'Update password',
    activeSessions: 'Active sessions',
    thisDevice: 'THIS DEVICE',
    lastActive: 'Last active',
    emptyNoSessions: 'No active sessions',
    emptyNoSessionsHint: 'Sessions from signed-in devices will appear here.',
    vaultKeyMgmt: 'Private Vault key',
    vaultKeyMgmtNote: 'The vault key exists only on your devices. AEGIS cannot reset it. If it is lost, vault contents are lost with it.',
    shareDefaults: 'Share link defaults',
    defaultExpiry: 'Default expiry',
    defaultScope: 'Default network scope',
    snapSchedule: 'Snapshot schedule',
    retention: 'Retention policy',
    retentionNote: 'Keep hourly for 24 h · daily for 30 d · weekly for 1 y',
    encKeys: 'Encryption keys',
    encKeysNote: 'At-rest keys rotate automatically every 90 days. Last rotation:',
    keyAlgorithm: 'Algorithm',
    keyId: 'Key ID',
    rotateNow: 'Rotate now',
    rotating: 'Rotating…',
    keyRotated: 'Key rotated',
    networkZones: 'Network zones',
    emptyNoZones: 'No network zones defined',
    zoneName: 'Zone name',
    zoneCidr: 'CIDR',
    addZone: 'Add zone',
    removeZone: 'Remove',
    zoneNamePlaceholder: 'e.g. R&D VLAN',
    zoneCidrPlaceholder: 'e.g. 10.20.0.0/24',
    invalidZone: 'Enter a name and a valid CIDR (e.g. 10.20.0.0/24)',
    backupTargets: 'Backup targets',
    hour1: '1 hour',
    hours24: '24 hours',
    days7: '7 days',
    days30: '30 days',
    everyHour: 'Every hour',
    every6h: 'Every 6 hours',
    daily: 'Daily',

    // misc
    justNow: 'just now',
    minAgo: '{n}m ago',
    hourAgo: '{n}h ago',
    dayAgo: '{n}d ago',
    empty: 'Nothing here yet',
    demoForce: 'Force state',
  },

  th: {
    productName: 'AEGIS Drive_LC',
    productTag: 'AUTONOMOUS EDGE-GUARD INFRASTRUCTURE SYSTEM',

    loginTitle: 'เข้าสู่ระบบ',
    loginSubtitle: 'NAS ปลอดภัย · ติดตั้งภายในองค์กร',
    username: 'ชื่อผู้ใช้',
    password: 'รหัสผ่าน',
    usernamePlaceholder: 'ชื่อ.นามสกุล',
    passwordPlaceholder: '••••••••',
    showPassword: 'แสดงรหัสผ่าน',
    hidePassword: 'ซ่อนรหัสผ่าน',
    rememberSession: 'จดจำเซสชันนี้',
    signIn: 'เข้าสู่ระบบ',
    signingIn: 'กำลังตรวจสอบ…',
    loginFailed: 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง',
    lockout: 'พยายามหลายครั้งเกินไป — ล็อก {s} วินาที',
    loginBlockedCsrf: 'คำขอถูกปฏิเสธ — ต้นทางไม่ตรงกัน กรุณาโหลดหน้าใหม่แล้วลองอีกครั้ง',
    loginNetwork: 'ติดต่อเซิร์ฟเวอร์ไม่ได้ ตรวจการเชื่อมต่อแล้วลองอีกครั้ง',
    loginTimeout: 'เซิร์ฟเวอร์ตอบกลับช้าเกินไป กรุณาลองอีกครั้ง',
    loginServerError: 'เซิร์ฟเวอร์ขัดข้อง — ยังไม่มีการตรวจรหัสผ่าน กรุณาลองอีกครั้ง',

    // สี่สถานะของจอ (loading = skeleton ไม่ต้องมีข้อความ)
    errLoadTitle: 'โหลดหน้านี้ไม่สำเร็จ',
    errLoadHint: 'เซิร์ฟเวอร์ Drive ไม่ตอบสนอง — ตรวจสอบว่าเซิร์ฟเวอร์กำลังทำงาน แล้วลองอีกครั้ง',
    errLoadTimeout: 'คำขอหมดเวลา — Edge node อาจกำลังโหลดหนัก ลองอีกครั้ง',
    retry: 'ลองใหม่',
    emptyNoFiles: 'ยังไม่มีไฟล์',
    emptyNoFilesHint: 'ไฟล์ที่อัปโหลดเข้า data lake จะแสดงที่นี่',
    emptyNoStorage: 'ยังไม่มีข้อมูลพื้นที่จัดเก็บ',
    emptyNoStorageHint: 'สถานะความจุ ดิสก์ และการสำรองข้อมูลจะแสดงที่นี่เมื่อโหนด Edge รายงานเข้ามา',
    emptyNoShares: 'ยังไม่มีลิงก์แชร์ที่ใช้งานอยู่',
    emptyNoSharesHint: 'สร้างลิงก์ทางซ้าย — ทุกลิงก์มีวันหมดอายุและขอบเขตเครือข่ายกำกับ',
    emptyNoSnapshots: 'ยังไม่มี snapshot',
    emptyNoSnapshotsHint: 'Snapshot อัตโนมัติจะแสดงที่นี่ตามตารางเวลา',
    emptyNoAudit: 'ยังไม่มีเหตุการณ์ audit',
    emptyNoAuditHint: 'การกระทำที่เกี่ยวข้องกับความปลอดภัยจะถูกบันทึกที่นี่',
    emptyNoUsers: 'ยังไม่มีบัญชีผู้ใช้',
    emptyNoActivity: 'ยังไม่มีกิจกรรมล่าสุด',
    emptyNoUploads: 'ยังไม่มีการอัปโหลด',
    emptyNoUploadsHint: 'ลากไฟล์มาวางด้านบนเพื่อจัดเก็บแบบเข้ารหัสบน NAS',
    dashLoginHistory: 'ประวัติการเข้าสู่ระบบ',
    dashLoginHistorySub: 'การเข้าสู่ระบบล่าสุดของคุณ — สถานะความปลอดภัยส่วนตัว',
    statSecurity: 'เหตุการณ์ความปลอดภัย',
    stFailed: 'ไม่สำเร็จ',
    confirmDeleteTitle: 'ลบออกจาก data lake?',
    confirmDeleteBody: '“{name}” จะถูกลบ — snapshot ที่ถ่ายไว้ก่อนหน้านี้ยังกู้คืนได้',
    actionFailed: 'ดำเนินการไม่สำเร็จ — เซิร์ฟเวอร์ไม่รับคำขอ ลองอีกครั้ง',
    layerNetwork: 'LAYER 0 · NETWORK',
    layerNetworkDesc: 'VPN + VLAN',
    layerApp: 'LAYER 1 · APPLICATION',
    layerAppDesc: 'ข้อมูลประจำตัว',
    layerStorage: 'LAYER 2 · STORAGE',
    layerStorageDesc: 'เข้ารหัสขณะจัดเก็บ',
    layerMeta: 'LAYER 3 · METADATA',
    layerMetaDesc: 'PostgreSQL',

    navDashboard: 'แดชบอร์ด',
    navFiles: 'ไฟล์',
    navVault: 'ห้องนิรภัยส่วนตัว',
    navUploads: 'อัปโหลด',
    navShares: 'ลิงก์แชร์ปลอดภัย',
    navSnapshots: 'สแนปช็อต',
    navStorage: 'พื้นที่เก็บ & สำรอง',
    navAudit: 'บันทึกตรวจสอบ',
    navAccess: 'ควบคุมสิทธิ์',
    navSettings: 'ตั้งค่า',
    navGroupWorkspace: 'พื้นที่ทำงาน',
    navGroupProtection: 'การปกป้อง',
    navGroupAdmin: 'ผู้ดูแลระบบ',
    storageMeter: 'พื้นที่เก็บ',
    upgradeStorage: 'อัปเกรดพื้นที่',
    of: 'จาก',
    collapseSidebar: 'ย่อแถบข้าง',
    expandSidebar: 'ขยายแถบข้าง',
    signOut: 'ออกจากระบบ',

    searchPlaceholder: 'ค้นหาไฟล์ ผู้คน การทำงาน…',
    searchSecRecent: 'ล่าสุด',
    searchSecSuggested: 'แนะนำ',
    searchSecFiles: 'ไฟล์',
    searchSecPeople: 'ผู้คน',
    searchSecActions: 'การทำงาน',
    searchNoRecent: 'ยังไม่มีไฟล์ล่าสุด',
    searchNoResults: 'ไม่พบผลลัพธ์สำหรับ “{q}”',
    searchNoResultsHint: 'ลองตรวจตัวสะกด หรือค้นด้วยชื่อไฟล์ ชื่อผู้ใช้ หรือชื่อหน้าจอ',
    searchJumpTo: 'ไปที่หน้านี้',
    searchUnavailable: 'ค้นหาไม่ได้ — ห้องนิรภัยส่วนตัวถูกเข้ารหัส',
    searchUnavailableVault: 'ค้นหาไม่พร้อมใช้งานในห้องนิรภัย — เนื้อหาถูกเข้ารหัสแบบ zero-knowledge',
    edgeNodeOnline: 'EDGE NODE · ออนไลน์',
    notifications: 'การแจ้งเตือน',
    previewAs: 'พรีวิว',
    previewAsTooltip: 'เครื่องมือสำหรับนักพัฒนา — สลับ role จำลองที่เซิร์ฟเวอร์ออกให้ ไม่ใช่ส่วนหนึ่งของการยืนยันตัวตน',

    dashTitle: 'แดชบอร์ด',
    statStorage: 'พื้นที่ที่ใช้',
    statFiles: 'ไฟล์ที่จัดทำดัชนี',
    statSessions: 'เซสชันที่ใช้งาน',
    statAlerts: 'แจ้งเตือนความสมบูรณ์ (24 ชม.)',
    vsLastWeek: 'เทียบสัปดาห์ก่อน',
    allClear: 'ปกติทั้งหมด',
    lakeHealth: 'สุขภาพ Data Lake',
    lakeSubtitle: 'สามชั้น · เรียลไทม์',
    tierApp: 'APPLICATION LAYER',
    tierMeta: 'METADATA LAYER',
    tierStorage: 'STORAGE LAYER',
    tierHealthy: 'ปกติ',
    tierDegraded: 'เสื่อมสภาพ',
    tierDown: 'ล่ม',
    latency: 'เวลาแฝง',
    activity: 'กิจกรรม',
    storageBreakdown: 'สัดส่วนพื้นที่เก็บ',
    transferActivity: 'กิจกรรมอัปโหลด / ดาวน์โหลด',
    uploads: 'อัปโหลด',
    downloads: 'ดาวน์โหลด',
    projected: 'คาดการณ์',
    demoControls: 'เดโม',

    filesTitle: 'ไฟล์',
    upload: 'อัปโหลด',
    newFolder: 'โฟลเดอร์ใหม่',
    gridView: 'มุมมองตาราง',
    listView: 'มุมมองรายการ',
    sortBy: 'เรียงตาม',
    sortName: 'ชื่อ',
    sortSize: 'ขนาด',
    sortModified: 'แก้ไขล่าสุด',
    colName: 'ชื่อ',
    colSize: 'ขนาด',
    colType: 'ชนิด',
    colModified: 'แก้ไขล่าสุด',
    colEncryption: 'การเข้ารหัส',
    encServer: 'ฝั่งเซิร์ฟเวอร์ · ค้นหาได้',
    encVault: 'ไซเฟอร์เท็กซ์ห้องนิรภัย',
    selected: 'รายการที่เลือก',
    download: 'ดาวน์โหลด',
    move: 'ย้าย',
    delete: 'ลบ',
    rename: 'เปลี่ยนชื่อ',
    createLink: 'สร้างลิงก์ปลอดภัย',
    verifySha: 'ตรวจสอบ SHA-256',
    viewMetadata: 'ดูเมทาดาทา',
    fileDetails: 'รายละเอียดไฟล์',
    size: 'ขนาด',
    type: 'ชนิด',
    uploader: 'ผู้อัปโหลด',
    uploadedAt: 'อัปโหลดเมื่อ',
    storagePath: 'พาธจัดเก็บ',
    integrity: 'ความสมบูรณ์',
    integrityOk: 'ตรวจสอบแล้ว',
    integrityPending: 'ยังไม่ได้ตรวจสอบ',
    integrityFail: 'ไม่ตรงกัน',
    verifyChecksum: 'ตรวจสอบเช็กซัม',
    verifying: 'กำลังตรวจสอบ…',
    integrityVerified: '✓ ความสมบูรณ์ถูกต้อง',
    integrityMismatch: '✕ เช็กซัมไม่ตรงกัน',
    copyHash: 'คัดลอกแฮช',
    copied: 'คัดลอกแล้ว',
    close: 'ปิด',

    vaultTitle: 'ห้องนิรภัยส่วนตัว',
    vaultWarning: 'เข้ารหัสแบบ ZERO-KNOWLEDGE · กุญแจหายคือกู้ไม่ได้',
    vaultCipherCaption: 'CIPHERTEXT · เซิร์ฟเวอร์อ่านไม่ได้',
    vaultLocked: 'ล็อกอยู่',
    vaultUnlocked: 'ปลดล็อกแล้ว',
    unlockVault: 'ปลดล็อกห้องนิรภัย',
    lockVault: 'ล็อกห้องนิรภัย',
    decrypt: 'ถอดรหัส',
    vaultKeyLabel: 'กุญแจห้องนิรภัย',
    vaultKeyNote: 'กุญแจถอดรหัสไฟล์ในเบราว์เซอร์นี้เท่านั้น ไม่ถูกส่งไปเซิร์ฟเวอร์ — เซิร์ฟเวอร์เก็บเพียงไซเฟอร์เท็กซ์ที่อ่านไม่ออก',
    vaultNoSearch: 'ไม่มีภาพตัวอย่าง ไม่มีการค้นหาเนื้อหา — นั่นแหละคือประเด็น',
    vaultWrongKey: 'ถอดรหัสไม่สำเร็จ — กุญแจนี้เปิดห้องนิรภัยนี้ไม่ได้',
    vaultUnlockUnavailable: 'เรียกใช้ตัวถอดรหัสในเบราว์เซอร์นี้ไม่ได้ — ยังไม่มีการตรวจกุญแจของคุณเลย ลองโหลดหน้าใหม่ ถ้ายังเป็นอยู่ แสดงว่าหน้านี้ถูกห้ามรัน WebAssembly',
    vaultSetupTitle: 'สร้างกุญแจห้องนิรภัย',
    vaultSetupIntro: 'กุญแจนี้แยกจากรหัสผ่านบัญชีของคุณ ถูกสร้างในเบราว์เซอร์นี้ และไม่ถูกส่งไปยัง AEGIS',
    vaultSetupCreate: 'สร้างห้องนิรภัย',
    vaultSetupNeeded: 'ยังไม่มีห้องนิรภัย',
    vaultSetupCta: 'ตั้งค่าห้องนิรภัย',
    vaultKeyConfirmLabel: 'พิมพ์กุญแจอีกครั้ง',
    vaultKeyMismatch: 'กุญแจสองครั้งไม่ตรงกัน',
    vaultKeyTooShort: 'ใช้อย่างน้อย 12 ตัวอักษร — กุญแจนี้คือสิ่งเดียวที่กั้นระหว่างผู้บุกรุกกับไฟล์ของคุณ',
    vaultSetupAck: 'ฉันเข้าใจว่าถ้าลืมกุญแจนี้ ไฟล์เหล่านี้จะหายถาวร AEGIS รีเซ็ตให้ไม่ได้',
    vaultDeriving: 'กำลังสร้างกุญแจ…',
    vaultDecrypting: 'กำลังถอดรหัส…',
    vaultDownload: 'ดาวน์โหลด',
    vaultAutoLocked: 'ล็อกห้องนิรภัยอัตโนมัติ หลังไม่มีการใช้งาน 10 นาที',
    vaultUnnamed: 'รายการที่อ่านไม่ออก',

    uploadsTitle: 'อัปโหลด',
    dropHere: 'ลากไฟล์มาวางที่นี่ หรือคลิกเพื่อเลือก',
    dropSub: 'ไฟล์ถูกเข้ารหัสก่อนแตะดิสก์',
    stStaged: 'เตรียมแล้ว',
    stEncrypting: 'กำลังเข้ารหัส',
    stTransferring: 'กำลังส่ง',
    stHashing: 'กำลังแฮช',
    stIndexed: 'จัดดัชนีแล้ว',
    recentUploads: 'อัปโหลดล่าสุด',
    simulateUpload: 'จำลองไฟล์ขาเข้า',

    sharesTitle: 'ลิงก์แชร์ปลอดภัย',
    newShare: 'สร้างลิงก์แชร์',
    shareFile: 'ไฟล์',
    expiry: 'อายุลิงก์',
    authMethod: 'การยืนยัน',
    authPassword: 'รหัสผ่าน',
    authOtc: 'รหัสใช้ครั้งเดียว',
    authNone: 'ไม่มี',
    networkScope: 'ขอบเขตเครือข่าย',
    scopeVlan: 'เฉพาะ VLAN บริษัท',
    scopeSubnet: 'ซับเน็ตที่กำหนด',
    scopeAny: 'เครือข่ายใดก็ได้',
    scopeDiagramNote: 'คำขอจากโซนที่ถูกบล็อกจะถูกไฟร์วอลล์ทิ้งก่อนถึงตัวไฟล์',
    zoneCompany: 'VLAN บริษัท',
    zoneGuest: 'VLAN แขก',
    zoneInternet: 'อินเทอร์เน็ต',
    createShare: 'สร้างลิงก์',
    activeLinks: 'ลิงก์ที่ใช้งานอยู่',
    colScope: 'ขอบเขต',
    colAuth: 'การยืนยัน',
    colExpiresIn: 'หมดอายุใน',
    colCreatedBy: 'สร้างโดย',
    colHits: 'ครั้งที่เปิด',
    revoke: 'เพิกถอน',
    revokeTitle: 'เพิกถอนลิงก์แชร์?',
    revokeBody: 'ลิงก์ของ “{name}” จะตายทันที ใครถือลิงก์อยู่จะไม่ได้อะไรเลย การกระทำนี้ย้อนกลับไม่ได้',
    confirmRevoke: 'เพิกถอนถาวร',
    cancel: 'ยกเลิก',
    expired: 'หมดอายุ',
    chipVlanOnly: 'VLAN เท่านั้น',
    chipSubnet: 'ซับเน็ต',
    chipAnyNetwork: 'ทุกเครือข่าย',

    snapshotsTitle: 'สแนปช็อต & กู้คืน',
    snapshotTimeline: 'ไทม์ไลน์',
    current: 'ปัจจุบัน',
    colId: 'ID',
    colTimestamp: 'เวลา',
    colDelta: 'ขนาดที่ต่าง',
    colVerified: 'ตรวจสอบ',
    rollback: 'ย้อนกลับ',
    rollbackTitle: 'ย้อนกลับไปยังสแนปช็อต?',
    rollbackWhatRestored: 'ทุกอย่างที่โวลุ่มมี ณ {time} จะกลับมา — ไฟล์ เมทาดาทา สิทธิ์',
    rollbackWhatLost: 'ทุกการเปลี่ยนแปลงหลังจากนั้นจะถูกทำลาย: การเขียน {delta}',
    rollbackTypeToConfirm: 'พิมพ์ ID ของสแนปช็อตเพื่อยืนยัน',
    rollbackConfirm: 'ย้อนกลับเดี๋ยวนี้',
    restoring: 'กำลังกู้คืนสแนปช็อต…',
    restored: 'กู้คืนสำเร็จ โวลุ่มกลับไปที่ {id} แล้ว',

    storageTitle: 'พื้นที่เก็บ & สำรอง',
    capacity: 'ความจุ',
    raidTitle: 'RAID 1 Mirror',
    synced: 'ซิงก์แล้ว',
    degraded: 'เสื่อมสภาพ',
    rebuilding: 'กำลังสร้างใหม่',
    unprotected: '⚠ ไร้การป้องกัน',
    diskFailed: 'ดิสก์เสียหาย',
    temperature: 'อุณหภูมิ',
    smart: 'SMART',
    powerOn: 'เปิดใช้งาน',
    hours: 'ชม.',
    backupSchedule: 'ตารางสำรองข้อมูล',
    colJob: 'งาน',
    colTarget: 'ปลายทาง',
    colFrequency: 'ความถี่',
    colLastRun: 'รอบล่าสุด',
    colStatus: 'สถานะ',
    colNextRun: 'รอบถัดไปใน',
    docs: 'เอกสาร',
    media: 'สื่อ',
    archives: 'ไฟล์บีบอัด',
    vaultSeg: 'ห้องนิรภัย',
    free: 'ว่าง',

    auditTitle: 'บันทึกตรวจสอบ',
    auditSubtitle: 'บันทึกต่อท้ายอย่างเดียว แก้ไขอะไรไม่ได้',
    colActor: 'ผู้กระทำ',
    colAction: 'การกระทำ',
    colTargetA: 'เป้าหมาย',
    colResult: 'ผลลัพธ์',
    colSourceIp: 'IP ต้นทาง',
    exportCsv: 'ส่งออก CSV',
    filterAll: 'ทั้งหมด',
    filterDenied: 'เฉพาะถูกปฏิเสธ',
    filterActor: 'ผู้กระทำ',
    filterAction: 'การกระทำ',
    filterRange: 'ช่วงเวลา',
    filterScope: 'ขอบเขต',
    filterStatus: 'สถานะ',
    filterActive: 'ยังใช้งานได้',
    filterExpiresWithin: 'หมดอายุภายใน',
    emptyNoAuditFiltered: 'ไม่มีเหตุการณ์ที่ตรงกับตัวกรอง',
    emptyNoSharesFiltered: 'ไม่มีลิงก์ที่ตรงกับตัวกรอง',
    resOk: 'สำเร็จ',
    resDenied: 'ปฏิเสธ',
    resBlocked: 'บล็อก',

    accessTitle: 'ควบคุมสิทธิ์',
    addUser: 'เพิ่มผู้ใช้',
    accessFilter: 'กรองด้วยชื่อหรือชื่อผู้ใช้…',
    accessFilterNone: 'ไม่พบผู้ใช้ที่ตรงกับ “{q}”',
    colUser: 'ผู้ใช้',
    colRole: 'บทบาท',
    colLastLogin: 'เข้าระบบล่าสุด',
    active: 'ใช้งานอยู่',
    suspended: 'ระงับ',
    pendingReset: 'รอตั้งรหัสใหม่',
    pendingResetHint: 'ยังใช้รหัสผ่านชั่วคราว — ถูกปิดกั้นทุกหน้าจนกว่าจะเปลี่ยนรหัส',
    neverLoggedIn: 'ยังไม่เคย',
    tempPasswordIntro: 'สร้างบัญชีแล้ว คัดลอกรหัสผ่านชั่วคราวนี้แล้วส่งต่อให้ผู้ใช้นอกช่องทางนี้ (เช่น พบหน้ากันหรือแชทที่ปลอดภัย) — ระบบจะไม่แสดงซ้ำอีก',
    tempPasswordLabel: 'รหัสผ่านชั่วคราว',
    copyTempPassword: 'คัดลอกรหัสผ่านชั่วคราว',
    copied: 'คัดลอกแล้ว',
    tempPasswordWarn: 'ผู้ใช้ต้องเปลี่ยนรหัสผ่านนี้ในการล็อกอินครั้งแรกก่อนใช้งานส่วนอื่นได้',
    done: 'เสร็จสิ้น',
    permMatrix: 'ตารางสิทธิ์',
    permUploadDl: 'อัปโหลด / ดาวน์โหลดไฟล์',
    permShare: 'สร้างลิงก์แชร์',
    permVault: 'ห้องนิรภัยส่วนตัว',
    permSnapRestore: 'กู้คืนสแนปช็อต',
    permAudit: 'อ่านบันทึกตรวจสอบ',
    permManageUsers: 'จัดการผู้ใช้และบทบาท',
    firewallNote: 'การแก้ไขโซนไฟร์วอลล์ต้องใช้สิทธิ์ระดับ OS บนโหนด edge — จัดการที่นั่น ไม่ใช่ที่นี่',
    roleAdmin: 'Admin',
    roleUser: 'DataLake-User',

    settingsTitle: 'ตั้งค่า',
    setAppearance: 'หน้าตา',
    setAccount: 'บัญชี',
    setSecurity: 'ความปลอดภัย & ความเป็นส่วนตัว',
    setStorageData: 'พื้นที่เก็บ & ข้อมูล',
    setAdmin: 'ผู้ดูแลระบบ',
    theme: 'ธีม',
    themeLight: 'สว่าง',
    themeDark: 'มืด',
    themeSystem: 'ตามระบบ',
    language: 'ภาษา',
    density: 'ความหนาแน่นการแสดงผล',
    densityComfortable: 'สบายตา',
    densityCompact: 'กะทัดรัด',
    profile: 'โปรไฟล์',
    changePassword: 'เปลี่ยนรหัสผ่าน',
    currentPassword: 'รหัสผ่านปัจจุบัน',
    newPassword: 'รหัสผ่านใหม่',
    updatePassword: 'อัปเดตรหัสผ่าน',
    activeSessions: 'เซสชันที่ใช้งาน',
    thisDevice: 'เครื่องนี้',
    lastActive: 'ใช้งานล่าสุด',
    emptyNoSessions: 'ยังไม่มีเซสชันที่ใช้งานอยู่',
    emptyNoSessionsHint: 'เซสชันจากอุปกรณ์ที่ล็อกอินจะแสดงที่นี่',
    vaultKeyMgmt: 'กุญแจห้องนิรภัย',
    vaultKeyMgmtNote: 'กุญแจอยู่บนอุปกรณ์ของคุณเท่านั้น AEGIS รีเซ็ตให้ไม่ได้ ถ้าหาย ข้อมูลในห้องนิรภัยหายตามไปด้วย',
    shareDefaults: 'ค่าเริ่มต้นลิงก์แชร์',
    defaultExpiry: 'อายุเริ่มต้น',
    defaultScope: 'ขอบเขตเครือข่ายเริ่มต้น',
    snapSchedule: 'ตารางสแนปช็อต',
    retention: 'นโยบายเก็บรักษา',
    retentionNote: 'รายชั่วโมงเก็บ 24 ชม. · รายวันเก็บ 30 วัน · รายสัปดาห์เก็บ 1 ปี',
    encKeys: 'กุญแจเข้ารหัส',
    encKeysNote: 'กุญแจ at-rest หมุนเวียนอัตโนมัติทุก 90 วัน หมุนล่าสุด:',
    keyAlgorithm: 'อัลกอริทึม',
    keyId: 'รหัสกุญแจ',
    rotateNow: 'หมุนกุญแจตอนนี้',
    rotating: 'กำลังหมุนกุญแจ…',
    keyRotated: 'หมุนกุญแจแล้ว',
    networkZones: 'โซนเครือข่าย',
    emptyNoZones: 'ยังไม่มีการกำหนดโซนเครือข่าย',
    zoneName: 'ชื่อโซน',
    zoneCidr: 'CIDR',
    addZone: 'เพิ่มโซน',
    removeZone: 'ลบ',
    zoneNamePlaceholder: 'เช่น VLAN R&D',
    zoneCidrPlaceholder: 'เช่น 10.20.0.0/24',
    invalidZone: 'กรอกชื่อและ CIDR ที่ถูกต้อง (เช่น 10.20.0.0/24)',
    backupTargets: 'ปลายทางสำรองข้อมูล',
    hour1: '1 ชั่วโมง',
    hours24: '24 ชั่วโมง',
    days7: '7 วัน',
    days30: '30 วัน',
    everyHour: 'ทุกชั่วโมง',
    every6h: 'ทุก 6 ชั่วโมง',
    daily: 'รายวัน',

    justNow: 'เมื่อครู่',
    minAgo: '{n} นาทีที่แล้ว',
    hourAgo: '{n} ชม.ที่แล้ว',
    dayAgo: '{n} วันที่แล้ว',
    empty: 'ยังไม่มีอะไรที่นี่',
    demoForce: 'บังคับสถานะ',
  },

  zh: {
    productName: 'AEGIS Drive_LC',
    productTag: 'AUTONOMOUS EDGE-GUARD INFRASTRUCTURE SYSTEM',

    loginTitle: '登录',
    loginSubtitle: '安全 NAS · 本地部署',
    username: '用户名',
    password: '密码',
    usernamePlaceholder: '名.姓',
    passwordPlaceholder: '••••••••',
    showPassword: '显示密码',
    hidePassword: '隐藏密码',
    rememberSession: '记住此会话',
    signIn: '登录',
    signingIn: '正在验证…',
    loginFailed: '用户名或密码不正确。',
    lockout: '尝试次数过多——锁定 {s} 秒',
    loginBlockedCsrf: '请求被拦截——来源不匹配。请重新加载页面后再试。',
    loginNetwork: '无法连接服务器。请检查网络后重试。',
    loginTimeout: '服务器响应超时。请重试。',
    loginServerError: '服务器错误——尚未校验凭据。请重试。',

    // 四种界面状态
    errLoadTitle: '无法加载此页面',
    errLoadHint: 'Drive 后端未响应。请确认服务器正在运行，然后重试。',
    errLoadTimeout: '请求超时——Edge 节点可能负载较高，请重试。',
    retry: '重试',
    emptyNoFiles: '暂无文件',
    emptyNoFilesHint: '上传到数据湖的文件将显示在此处。',
    emptyNoStorage: '暂无存储数据',
    emptyNoStorageHint: '边缘节点上报后，容量、磁盘与备份状态将显示在此处。',
    emptyNoShares: '暂无有效共享链接',
    emptyNoSharesHint: '在左侧创建链接——每个链接均带有有效期和网络范围。',
    emptyNoSnapshots: '暂无快照',
    emptyNoSnapshotsHint: '自动快照将按计划显示在此处。',
    emptyNoAudit: '暂无审计事件',
    emptyNoAuditHint: '与安全相关的操作将记录在此处。',
    emptyNoUsers: '暂无用户账户',
    emptyNoActivity: '暂无最近活动',
    emptyNoUploads: '暂无上传',
    emptyNoUploadsHint: '将文件拖放到上方，以加密方式存储到 NAS。',
    dashLoginHistory: '登录历史',
    dashLoginHistorySub: '您最近的登录记录——个人安全状态',
    statSecurity: '安全事件',
    stFailed: '失败',
    confirmDeleteTitle: '从数据湖中删除？',
    confirmDeleteBody: '“{name}”将被删除——此前创建的快照仍可恢复它。',
    actionFailed: '操作失败——服务器未接受请求，请重试。',
    layerNetwork: 'LAYER 0 · NETWORK',
    layerNetworkDesc: 'VPN + VLAN',
    layerApp: 'LAYER 1 · APPLICATION',
    layerAppDesc: '凭据',
    layerStorage: 'LAYER 2 · STORAGE',
    layerStorageDesc: '静态加密',
    layerMeta: 'LAYER 3 · METADATA',
    layerMetaDesc: 'PostgreSQL',

    navDashboard: '仪表盘',
    navFiles: '文件',
    navVault: '私密保险库',
    navUploads: '上传',
    navShares: '安全分享',
    navSnapshots: '快照',
    navStorage: '存储与备份',
    navAudit: '审计日志',
    navAccess: '访问控制',
    navSettings: '设置',
    navGroupWorkspace: '工作区',
    navGroupProtection: '防护',
    navGroupAdmin: '管理',
    storageMeter: '存储',
    upgradeStorage: '升级存储',
    of: '/',
    collapseSidebar: '收起侧栏',
    expandSidebar: '展开侧栏',
    signOut: '退出登录',

    searchPlaceholder: '搜索文件、人员、操作…',
    searchSecRecent: '最近',
    searchSecSuggested: '建议',
    searchSecFiles: '文件',
    searchSecPeople: '人员',
    searchSecActions: '操作',
    searchNoRecent: '暂无最近文件',
    searchNoResults: '没有与“{q}”匹配的结果',
    searchNoResultsHint: '请检查拼写，或尝试文件名、人员或页面名称。',
    searchJumpTo: '跳转到该页面',
    searchUnavailable: '无法搜索 — 私密保险库已加密',
    searchUnavailableVault: '保险库内无法搜索 — 其内容采用零知识加密',
    edgeNodeOnline: 'EDGE NODE · 在线',
    notifications: '通知',
    previewAs: '预览',
    previewAsTooltip: '开发者预览 — 切换模拟服务器签发的角色，不属于认证流程。',

    dashTitle: '仪表盘',
    statStorage: '已用存储',
    statFiles: '已索引文件',
    statSessions: '活动会话',
    statAlerts: '完整性警报 (24h)',
    vsLastWeek: '对比上周',
    allClear: '一切正常',
    lakeHealth: '数据湖健康',
    lakeSubtitle: '三层 · 实时',
    tierApp: 'APPLICATION LAYER',
    tierMeta: 'METADATA LAYER',
    tierStorage: 'STORAGE LAYER',
    tierHealthy: '健康',
    tierDegraded: '降级',
    tierDown: '宕机',
    latency: '延迟',
    activity: '动态',
    storageBreakdown: '存储构成',
    transferActivity: '上传 / 下载活动',
    uploads: '上传',
    downloads: '下载',
    projected: '预测',
    demoControls: '演示',

    filesTitle: '文件',
    upload: '上传',
    newFolder: '新建文件夹',
    gridView: '网格视图',
    listView: '列表视图',
    sortBy: '排序',
    sortName: '名称',
    sortSize: '大小',
    sortModified: '修改时间',
    colName: '名称',
    colSize: '大小',
    colType: '类型',
    colModified: '修改时间',
    colEncryption: '加密',
    encServer: '服务端 · 可索引',
    encVault: '保险库密文',
    selected: '已选',
    download: '下载',
    move: '移动',
    delete: '删除',
    rename: '重命名',
    createLink: '创建安全链接',
    verifySha: '校验 SHA-256',
    viewMetadata: '查看元数据',
    fileDetails: '文件详情',
    size: '大小',
    type: '类型',
    uploader: '上传者',
    uploadedAt: '上传时间',
    storagePath: '存储路径',
    integrity: '完整性',
    integrityOk: '已校验',
    integrityPending: '尚未校验',
    integrityFail: '不匹配',
    verifyChecksum: '校验校验和',
    verifying: '校验中…',
    integrityVerified: '✓ 完整性已验证',
    integrityMismatch: '✕ 校验和不匹配',
    copyHash: '复制哈希',
    copied: '已复制',
    close: '关闭',

    vaultTitle: '私密保险库',
    vaultWarning: '零知识加密 · 密钥丢失不可恢复',
    vaultCipherCaption: 'CIPHERTEXT · 服务器无法读取',
    vaultLocked: '已锁定',
    vaultUnlocked: '已解锁',
    unlockVault: '解锁保险库',
    lockVault: '锁定保险库',
    decrypt: '解密',
    vaultKeyLabel: '保险库密钥',
    vaultKeyNote: '密钥仅在此浏览器内解密文件，永不发送到服务器 — 服务器只保存它无法读取的密文。',
    vaultNoSearch: '没有缩略图，没有内容搜索 — 这正是重点。',
    vaultWrongKey: '解密失败 — 该密钥无法打开此保险库。',
    vaultUnlockUnavailable: '无法在此浏览器中运行解密引擎——尚未校验你的密钥。请重新加载页面；若仍然如此，说明该页面被禁止运行 WebAssembly。',
    vaultSetupTitle: '创建保险库密钥',
    vaultSetupIntro: '此密钥与账户密码相互独立。它在此浏览器中生成，永不发送给 AEGIS。',
    vaultSetupCreate: '创建保险库',
    vaultSetupNeeded: '尚未创建保险库',
    vaultSetupCta: '设置保险库',
    vaultKeyConfirmLabel: '再次输入密钥',
    vaultKeyMismatch: '两次输入不一致。',
    vaultKeyTooShort: '至少使用 12 个字符。这把密钥是攻击者与你的文件之间唯一的屏障。',
    vaultSetupAck: '我明白：一旦丢失此密钥，这些文件将永久丢失，AEGIS 无法重置。',
    vaultDeriving: '正在派生密钥…',
    vaultDecrypting: '正在解密…',
    vaultDownload: '下载',
    vaultAutoLocked: '闲置 10 分钟后保险库已自动重新锁定。',
    vaultUnnamed: '无法读取的条目',

    uploadsTitle: '上传',
    dropHere: '拖放文件到此处，或点击选择',
    dropSub: '文件在写入磁盘前已加密',
    stStaged: '已就绪',
    stEncrypting: '加密中',
    stTransferring: '传输中',
    stHashing: '哈希中',
    stIndexed: '已索引',
    recentUploads: '最近上传',
    simulateUpload: '模拟传入文件',

    sharesTitle: '安全分享',
    newShare: '新建分享链接',
    shareFile: '文件',
    expiry: '有效期',
    authMethod: '验证',
    authPassword: '密码',
    authOtc: '一次性验证码',
    authNone: '无',
    networkScope: '网络范围',
    scopeVlan: '仅公司 VLAN',
    scopeSubnet: '指定子网',
    scopeAny: '任意网络',
    scopeDiagramNote: '来自被阻止区域的请求会在触及文件之前被防火墙丢弃。',
    zoneCompany: '公司 VLAN',
    zoneGuest: '访客 VLAN',
    zoneInternet: '互联网',
    createShare: '创建链接',
    activeLinks: '活动链接',
    colScope: '范围',
    colAuth: '验证',
    colExpiresIn: '剩余时间',
    colCreatedBy: '创建者',
    colHits: '访问次数',
    revoke: '撤销',
    revokeTitle: '撤销分享链接？',
    revokeBody: '“{name}” 的链接将立即失效，持有链接者将一无所获。此操作无法撤销。',
    confirmRevoke: '永久撤销',
    cancel: '取消',
    expired: '已过期',
    chipVlanOnly: '仅 VLAN',
    chipSubnet: '子网',
    chipAnyNetwork: '任意网络',

    snapshotsTitle: '快照与恢复',
    snapshotTimeline: '时间线',
    current: '当前',
    colId: 'ID',
    colTimestamp: '时间',
    colDelta: '大小变化',
    colVerified: '已校验',
    rollback: '回滚',
    rollbackTitle: '回滚到此快照？',
    rollbackWhatRestored: '卷在 {time} 时的一切都会恢复 — 文件、元数据、权限。',
    rollbackWhatLost: '此后所有更改将被销毁：{delta} 的写入。',
    rollbackTypeToConfirm: '输入快照 ID 以确认',
    rollbackConfirm: '立即回滚',
    restoring: '正在恢复快照…',
    restored: '快照已恢复。卷已回到 {id}。',

    storageTitle: '存储与备份',
    capacity: '容量',
    raidTitle: 'RAID 1 镜像',
    synced: '已同步',
    degraded: '降级',
    rebuilding: '重建中',
    unprotected: '⚠ 无保护',
    diskFailed: '磁盘丢失',
    temperature: '温度',
    smart: 'SMART',
    powerOn: '通电时长',
    hours: '小时',
    backupSchedule: '备份计划',
    colJob: '任务',
    colTarget: '目标',
    colFrequency: '频率',
    colLastRun: '上次运行',
    colStatus: '状态',
    colNextRun: '下次运行',
    docs: '文档',
    media: '媒体',
    archives: '归档',
    vaultSeg: '保险库',
    free: '可用',

    auditTitle: '审计日志',
    auditSubtitle: '仅追加。此处内容不可编辑。',
    colActor: '操作者',
    colAction: '操作',
    colTargetA: '目标',
    colResult: '结果',
    colSourceIp: '来源 IP',
    exportCsv: '导出 CSV',
    filterAll: '全部',
    filterDenied: '仅被拒绝',
    filterActor: '操作者',
    filterAction: '操作',
    filterRange: '时间范围',
    filterScope: '范围',
    filterStatus: '状态',
    filterActive: '有效',
    filterExpiresWithin: '将在此期限内过期',
    emptyNoAuditFiltered: '没有符合筛选条件的事件',
    emptyNoSharesFiltered: '没有符合筛选条件的链接',
    resOk: '成功',
    resDenied: '拒绝',
    resBlocked: '阻止',

    accessTitle: '访问控制',
    addUser: '添加用户',
    accessFilter: '按姓名或用户名筛选…',
    accessFilterNone: '没有与“{q}”匹配的用户',
    colUser: '用户',
    colRole: '角色',
    colLastLogin: '最近登录',
    active: '活跃',
    suspended: '停用',
    pendingReset: '待重设密码',
    pendingResetHint: '仍在使用临时密码——在更改之前将被阻止访问所有页面。',
    neverLoggedIn: '从未',
    tempPasswordIntro: '账户已创建。请复制此临时密码并通过带外方式（如当面告知或安全聊天）转交给用户——此密码不会再次显示。',
    tempPasswordLabel: '临时密码',
    copyTempPassword: '复制临时密码',
    copied: '已复制',
    tempPasswordWarn: '用户必须在首次登录时重设此密码，之后才能使用其他功能。',
    done: '完成',
    permMatrix: '权限矩阵',
    permUploadDl: '上传 / 下载文件',
    permShare: '创建分享链接',
    permVault: '私密保险库',
    permSnapRestore: '恢复快照',
    permAudit: '读取审计日志',
    permManageUsers: '管理用户与角色',
    firewallNote: '防火墙区域更改需要边缘节点上的 OS 特权 — 在节点上管理，而非此处。',
    roleAdmin: 'Admin',
    roleUser: 'DataLake-User',

    settingsTitle: '设置',
    setAppearance: '外观',
    setAccount: '账户',
    setSecurity: '安全与隐私',
    setStorageData: '存储与数据',
    setAdmin: '管理',
    theme: '主题',
    themeLight: '浅色',
    themeDark: '深色',
    themeSystem: '跟随系统',
    language: '语言',
    density: '显示密度',
    densityComfortable: '舒适',
    densityCompact: '紧凑',
    profile: '个人资料',
    changePassword: '修改密码',
    currentPassword: '当前密码',
    newPassword: '新密码',
    updatePassword: '更新密码',
    activeSessions: '活动会话',
    thisDevice: '本设备',
    lastActive: '最近活动',
    emptyNoSessions: '暂无活动会话',
    emptyNoSessionsHint: '已登录设备的会话将显示在此处。',
    vaultKeyMgmt: '保险库密钥',
    vaultKeyMgmtNote: '密钥只存在于你的设备上。AEGIS 无法为你重置。密钥丢失，保险库内容随之丢失。',
    shareDefaults: '分享链接默认值',
    defaultExpiry: '默认有效期',
    defaultScope: '默认网络范围',
    snapSchedule: '快照计划',
    retention: '保留策略',
    retentionNote: '每小时保留 24 小时 · 每日保留 30 天 · 每周保留 1 年',
    encKeys: '加密密钥',
    encKeysNote: '静态密钥每 90 天自动轮换。上次轮换：',
    keyAlgorithm: '算法',
    keyId: '密钥 ID',
    rotateNow: '立即轮换',
    rotating: '正在轮换…',
    keyRotated: '密钥已轮换',
    networkZones: '网络区域',
    emptyNoZones: '尚未定义网络区域',
    zoneName: '区域名称',
    zoneCidr: 'CIDR',
    addZone: '添加区域',
    removeZone: '移除',
    zoneNamePlaceholder: '例如 R&D VLAN',
    zoneCidrPlaceholder: '例如 10.20.0.0/24',
    invalidZone: '请输入名称和有效的 CIDR（例如 10.20.0.0/24）',
    backupTargets: '备份目标',
    hour1: '1 小时',
    hours24: '24 小时',
    days7: '7 天',
    days30: '30 天',
    everyHour: '每小时',
    every6h: '每 6 小时',
    daily: '每日',

    justNow: '刚刚',
    minAgo: '{n} 分钟前',
    hourAgo: '{n} 小时前',
    dayAgo: '{n} 天前',
    empty: '这里还没有内容',
    demoForce: '强制状态',
  },
}

/** Simple template fill: t('revokeBody', { name }) */
export function makeT(lang) {
  const table = STRINGS[lang] ?? STRINGS.en
  return (key, vars) => {
    let s = table[key] ?? STRINGS.en[key] ?? key
    if (vars) for (const [k, v] of Object.entries(vars)) s = s.replaceAll(`{${k}}`, String(v))
    return s
  }
}
