// tests/contentSecurityPolicy.test.js — AEGIS Drive (IDEA1) · the Content-Security-Policy
// header the browser actually receives.
//
// PR #40 shipped the Private Vault media preview and it failed in a real browser:
// the vault unlocked, the Preview command worked, the modal opened, the decrypted
// metadata was correct, the MIME type read `image/png`, both sizes were displayed,
// and an <img> element was in the DOM — but the picture rendered as a broken-image
// icon. Nothing in the preview pipeline was wrong. The application's own CSP was
// refusing the blob: URL that pipeline exists to create:
//
//   img-src 'self' data:        ← no blob:, so <img src="blob:…"> is blocked
//   (no media-src at all)       ← falls back to default-src 'self', so <video> too
//
// That failure is invisible to every screen-level test, because jsdom does not
// enforce CSP and never fetches an object URL. So this suite tests the header
// itself — generated by the real middleware and read off a real HTTP response —
// rather than grepping the source for a substring.
//
// The change being pinned is deliberately narrow. blob: is a same-tab data
// source, not a network destination: the plaintext exists only inside the
// authenticated browser tab, for as long as the preview is open, and the server
// still never receives plaintext, a filename, a MIME type, a KEK or a DEK. What
// keeps that from being a script-execution hole is the other half of the
// contract, asserted here just as hard: script-src and default-src must NOT gain
// blob:. A blob URL may be displayed; it may never be executed.
import test from 'node:test'
import assert from 'node:assert/strict'

process.env.NODE_ENV = 'test'
process.env.SESSION_SECRET = 'csp-test-session-secret-not-used-in-production'

// Dynamic, so the environment above is set before any module reads it at load
// time — the same ordering the rest of the server suites rely on.
const { securityHeaders } = await import('../server/middleware/securityHeaders.js')
const { previewKindFor } = await import('../src/lib/vaultPreview.js')
const { createApp } = await import('../server/app.js')

const TEST_ENV = { NODE_ENV: 'test', SESSION_SECRET: 'csp-test-secret' }

/* ── reading the policy the way a browser reads it ─────────────────── */

/** Run the real middleware and return the exact CSP string it emitted. */
function generatedPolicy() {
  const headers = new Map()
  const res = { setHeader: (name, value) => headers.set(String(name).toLowerCase(), value) }
  let nextCalls = 0
  securityHeaders({}, res, () => { nextCalls += 1 })
  assert.equal(nextCalls, 1, 'the middleware must hand the request on exactly once')
  const policy = headers.get('content-security-policy')
  assert.equal(typeof policy, 'string', 'a Content-Security-Policy header must be set')
  return policy
}

/**
 * Parse a policy into directive → sources the way a user agent does: directives
 * split on ';', sources split on ASCII whitespace, directive names
 * case-insensitive. Keyword sources keep their quotes, because `self` and
 * `'self'` are not the same token to a browser.
 */
function parsePolicy(policy) {
  const directives = new Map()
  for (const chunk of policy.split(';')) {
    const parts = chunk.trim().split(/\s+/).filter(Boolean)
    if (parts.length === 0) continue
    const name = parts[0].toLowerCase()
    // A browser honours the FIRST occurrence of a directive and ignores repeats,
    // so a duplicate must not be able to look like a widening — or a narrowing.
    assert.equal(directives.has(name), false, `directive ${name} is declared twice`)
    directives.set(name, parts.slice(1))
  }
  return directives
}

/** Sources for one directive, following the fallback a browser applies. */
function effectiveSources(directives, name, fallback = 'default-src') {
  if (directives.has(name)) return directives.get(name)
  return directives.get(fallback) ?? null
}

/** Boot the production app and read the CSP off a real HTTP response. */
async function withServer(run) {
  const app = createApp({ env: TEST_ENV })
  const server = app.listen(0, '127.0.0.1')
  await new Promise((resolve) => server.once('listening', resolve))
  try {
    await run(`http://127.0.0.1:${server.address().port}`)
  } finally {
    await new Promise((resolve) => server.close(resolve))
  }
}

/* ── the regression this task exists to fix ────────────────────────── */

test('img-src admits the local object URLs the vault preview creates', () => {
  const img = parsePolicy(generatedPolicy()).get('img-src')
  assert.ok(img, 'img-src is declared explicitly, not left to default-src')

  // The exact failure observed in production: <img src="blob:…"> was blocked.
  assert.ok(img.includes('blob:'), `img-src must allow blob: — got "${img.join(' ')}"`)
  assert.ok(img.includes("'self'"), 'same-origin images stay allowed')
  assert.ok(img.includes('data:'), 'bundler-inlined favicons and small assets stay allowed')

  // Narrow: the addition is one token, not an opening.
  assert.deepEqual([...img].sort(), ["'self'", 'blob:', 'data:'].sort(),
    'img-src gained blob: and nothing else — no wildcard, no remote host')
})

test('media-src is declared and admits the vault video object URL', () => {
  const media = parsePolicy(generatedPolicy()).get('media-src')
  assert.ok(media, 'media-src is declared explicitly — inheriting default-src blocked <video src="blob:…">')

  assert.ok(media.includes('blob:'), `media-src must allow blob: — got "${media.join(' ')}"`)
  assert.ok(media.includes("'self'"), 'same-origin media stays allowed')
  assert.deepEqual([...media].sort(), ["'self'", 'blob:'].sort(),
    'media-src is exactly self + blob:; decrypted video never arrives as a data: URL, so data: is not granted')
})

test('the header a browser actually receives carries both grants', async () => {
  // The middleware could be correct and still not be mounted. This asserts the
  // response, not the module.
  await withServer(async (baseUrl) => {
    const res = await fetch(`${baseUrl}/healthz`)
    const served = res.headers.get('content-security-policy')
    assert.ok(served, 'every response carries a CSP, including the unauthenticated health probe')
    assert.equal(served, generatedPolicy(), 'the served policy is the one the middleware generates')

    const directives = parsePolicy(served)
    assert.ok(directives.get('img-src').includes('blob:'))
    assert.ok(directives.get('media-src').includes('blob:'))
    assert.equal(directives.get('script-src').includes('blob:'), false)
  })
})

/* ── the other half of the contract: display, never execute ────────── */

test('blob: is not granted to any directive that can run or fetch code', () => {
  const directives = parsePolicy(generatedPolicy())

  // script-src is what makes the img-src/media-src grant safe. A blob: URL that
  // can only be displayed is inert; one that can be loaded as script is an
  // execution sink for attacker-controlled bytes.
  const script = directives.get('script-src')
  assert.deepEqual(script, ["'self'", "'wasm-unsafe-eval'"],
    'script-src is unchanged: no blob:, no unsafe-inline, no unsafe-eval')
  assert.equal(script.includes('blob:'), false, 'a blob URL must never be executable')

  // default-src is the fallback for every directive not named, including
  // worker-src and script-src-elem. Granting blob: there would grant it
  // everywhere by the back door.
  const dflt = directives.get('default-src')
  assert.deepEqual(dflt, ["'self'"], 'default-src stays exactly self')
  assert.equal(dflt.includes('blob:'), false, 'blob: must not leak in through the fallback')

  for (const name of ['style-src', 'font-src', 'connect-src', 'form-action', 'base-uri', 'object-src']) {
    assert.equal(effectiveSources(directives, name).includes('blob:'), false, `${name} must not admit blob:`)
  }

  // A blob: worker would execute attacker bytes in the app origin; these must
  // resolve through default-src 'self' rather than being granted separately.
  for (const name of ['worker-src', 'child-src', 'script-src-elem', 'frame-src']) {
    assert.equal(effectiveSources(directives, name).includes('blob:'), false, `${name} resolves without blob:`)
  }
})

test('the surrounding policy is untouched by this fix', () => {
  const policy = generatedPolicy()
  const directives = parsePolicy(policy)

  assert.deepEqual(directives.get('object-src'), ["'none'"],
    "object-src stays 'none' — decrypted content is never handed to <object>/<embed>")
  assert.deepEqual(directives.get('frame-ancestors'), ["'none'"], 'clickjacking defence unchanged')
  assert.deepEqual(directives.get('connect-src'), ["'self'"],
    'connect-src stays scoped to this origin — no exfiltration path was opened')
  assert.deepEqual(directives.get('style-src'), ["'self'"])
  assert.deepEqual(directives.get('font-src'), ["'self'"])
  assert.deepEqual(directives.get('base-uri'), ["'none'"])
  assert.deepEqual(directives.get('form-action'), ["'self'"])

  assert.doesNotMatch(policy, /'unsafe-inline'/, "no 'unsafe-inline' was introduced")
  assert.doesNotMatch(policy, /(^|[^-])'unsafe-eval'/, "no bare 'unsafe-eval' was introduced")

  // A wildcard source, or a whole scheme opened, would make the narrow grants
  // above meaningless.
  for (const [name, sources] of directives) {
    for (const source of sources) {
      assert.notEqual(source, '*', `${name} must not use a wildcard`)
      assert.equal(/^https?:$/.test(source), false, `${name} must not open a whole scheme (${source})`)
      assert.equal(source.startsWith('*.'), false, `${name} must not use a host wildcard (${source})`)
    }
  }
})

test('the non-CSP security headers are unchanged', async () => {
  await withServer(async (baseUrl) => {
    const res = await fetch(`${baseUrl}/healthz`)
    assert.equal(res.headers.get('x-frame-options'), 'DENY')
    assert.equal(res.headers.get('x-content-type-options'), 'nosniff')
    assert.equal(res.headers.get('referrer-policy'), 'no-referrer')
    assert.equal(res.headers.get('strict-transport-security'), 'max-age=31536000; includeSubDomains')
    assert.equal(res.headers.get('permissions-policy'), 'camera=(), microphone=(), geolocation=(), payment=()')
    assert.equal(res.headers.get('x-powered-by'), null, 'Express is still not announcing itself')
  })
})

/* ── the CSP grant does not widen what may be previewed ────────────── */

test('allowing blob: media does not widen the preview allowlist', () => {
  // The CSP now permits a blob: image or video to load. The application-level
  // allowlist is a separate, independent control and is unchanged: the types
  // that are dangerous to render inline are refused before a blob URL is ever
  // minted, so there are two locks on the same door rather than one.
  for (const mime of [
    'image/svg+xml',                // an XML document; can carry <script>/<foreignObject>
    'image/svg+xml; charset=utf-8', // a parameter cannot smuggle it past
    'text/html',
    'application/pdf',
    'application/octet-stream',
    'application/zip',
    'text/plain',
  ]) {
    assert.equal(previewKindFor(mime), null, `${mime} is still download-only`)
  }

  // And the types that legitimately need the CSP grant still resolve.
  assert.equal(previewKindFor('image/png'), 'image')
  assert.equal(previewKindFor('video/mp4'), 'video')
})

test('no document-embedding element is given a CSP source it could use', () => {
  const directives = parsePolicy(generatedPolicy())
  // object-src 'none' kills <object>/<embed> outright; frame-src falls back to
  // default-src 'self', and frame-ancestors 'none' blocks the reverse direction.
  // Preview therefore has no path to hand decrypted bytes to a nested browsing
  // context, even if a future edit tried.
  assert.deepEqual(directives.get('object-src'), ["'none'"])
  assert.deepEqual(effectiveSources(directives, 'frame-src'), ["'self'"])
  assert.equal(effectiveSources(directives, 'frame-src').includes('blob:'), false)
  assert.equal(effectiveSources(directives, 'frame-src').includes('data:'), false)
})

/* ── LFT-V2-E3 · การสตรีม preview ต้องไม่ทำให้ CSP กว้างขึ้นแม้แต่นิดเดียว ────────
   The large-video preview path registers a same-origin Service Worker and points
   <video> at a virtual same-origin URL. Both are already covered by the policy as
   it stands, and this suite exists to keep it that way: the moment somebody adds
   a directive "to make the preview work", that is the signal something is being
   fetched from somewhere it should not be. */

test('the streamed preview needs no new CSP source — it is all same-origin', () => {
  const policy = parsePolicy(generatedPolicy())

  // The virtual URL is same-origin, so 'self' in media-src already covers it.
  // No blob:, no data:, and above all no remote origin is required for playback.
  const media = policy.get('media-src')
  assert.ok(media.includes("'self'"), 'the virtual preview URL is same-origin')
  assert.deepEqual(media.filter((src) => src.includes('://')), [],
    'a remote source in media-src would mean vault plaintext is being fetched off-origin')

  // worker-src is deliberately NOT declared: it falls back to default-src 'self',
  // which is exactly the grant a same-origin Service Worker needs. Declaring it
  // would add a directive to maintain without changing what is permitted.
  assert.equal(policy.has('worker-src'), false,
    'worker-src must stay undeclared and inherit default-src — adding it changes nothing but the maintenance burden')
  assert.equal(policy.has('child-src'), false, 'child-src likewise stays undeclared')
  assert.deepEqual(policy.get('default-src'), ["'self'"],
    'the Service Worker script is same-origin, so default-src must remain exactly \'self\'')
})

test('the preview Service Worker cannot become a route to off-origin bytes', () => {
  const policy = parsePolicy(generatedPolicy())

  // The worker fetches ciphertext with the page's own credentials. connect-src
  // bounds where that can go, and it must stay same-origin only: a worker that
  // could reach another origin is an exfiltration path with a key in its hand.
  assert.deepEqual(policy.get('connect-src'), ["'self'"],
    'the preview worker holds a DEK — connect-src must never leave this origin')

  // And the worker script itself is still just a script: it gains no execution
  // privilege the page does not already have.
  const script = policy.get('script-src')
  assert.equal(script.includes('blob:'), false, 'blob: must never become executable')
  assert.deepEqual(script.filter((src) => src.includes('://')), [],
    'no remote script origin may be introduced by the preview work')
})
